### ISSUE TITLE
Minor issue on color of circles in Fig. 2.3

### ISSUE THREAD

**Issue by linker81** [udlbook/udlbook#10]
In caption of Fig. 2.3 "The three circles represent the three lines from figure 2.2b-d", the two circles related to 2.2b and 2.2d have the same color of the relative lines, but the circle related to 2.2c has a different color.

**Comment by udlbook** [comment]
Done!  There's no such thing as a minor issue.  Happy to hear about this kind of thing!

**Comment by udlbook** [comment]
BTW, If you mail your name to udlbookmail@gmail.com,  I'll add you to the acknowledgments at the front of the book.  Thanks so much for reading and giving feedback!
