### ISSUE TITLE
A small mistake in the book (Section 7.5.1). 

### ISSUE THREAD

**Issue by ermiah** [udlbook/udlbook#102]
I'm reading through this excellent book, and I think I have found a small mistake in section 7.5.1, the first line of page 109. 
It reads as: 
`The expectation (mean) $\mathbb{E}[f_i]$ of the intermediate values $f_i$ is:  `

whereas it should read as: 
`The expectation (mean) $\mathbb{E}[f'_i]$ of the intermediate values $f'_i$ is:  `

both $f_i$s should be replaced with $f'_i$. 

![Screenshot 2023-11-29 012729](https://github.com/udlbook/udlbook/assets/12352586/fb1a7ad5-a692-41f1-bf71-e46a2f2b81e7)

**Comment by udlbook** [comment]
Thanks!  I have fixed this now.  Apologies that it took so long.  If you send me your full name to the e-mail address on the front of the draft, I'd be happy to add you to the acknowledgements.   

Let me know if you find any more!
