### ISSUE TITLE
Small errata in Inroduction

### ISSUE THREAD

**Issue by dagap** [udlbook/udlbook#103]
```
Generative models with latent variables can also benefit supervised learning models
where the outputs have structure (figure 1.4)
``` 
[Page 11]

I think you mean figure 1.12

**Comment by udlbook** [comment]
Hi -  

Apologies for taking so long to get back to you.  Completely swamped! Anyway, I do actually mean figure 1.4 which refers to the "output has structure" part.  I could add the other figure reference as well, but it would make the sentence a bit clunky.  Gonna leave this for now and update if someone else brings it up.

Thanks so much for writing though.  I really appreciate that you took the time.  Do let me know if there is anything else you find ambiguous or possibly wrong. I do eventually get around to replying to everyone.
