### ISSUE TITLE
Typo in equation on page 49

### ISSUE THREAD

**Issue by gavrie** [udlbook/udlbook#106]
On page 49, in equation 4.14:

`y = φ′0+φ′h′,`

Should be:

`y' = φ′0+φ′h′,`

**Comment by udlbook** [comment]
Hi Gavrie, 

Thank you so much. I have fixed this now and added your name to the acknowledgements.  It will be updated in the next printing (in about a year) and in the next online version.

Please let me know if you find anything else.  I do get around to fixing all of these tiny things.

Simon

**Comment by gavrie** [comment]
Hi Simon,

Thanks for the book, it really helps me to understand things that I've considered as "black boxes"!
Glad to help, and I'll report if I find anything further.
