### ISSUE TITLE
Expected exception is not thrown in Chap03/3_3_Shallow_Network_Regions.ipynb when $D_i > D$

### ISSUE THREAD

**Issue by yrahal** [udlbook/udlbook#110]
When $D_i > D$, it is expected that the calculation of the number of regions fails, but math.comb(n, k) evaluates to 0 when k > n (see https://docs.python.org/3/library/math.html#math.comb) so the final computation is actually correct (2ˆD)

![Screenshot 2023-12-13 at 20 09 49](https://github.com/udlbook/udlbook/assets/10063907/2729e6a6-5b9d-4334-9363-662965925575)

**Comment by udlbook** [comment]
Thanks so much for your help.  Somebody proposed using math.comb() as it is faster than other methods, and I guess this no longer breaks. I have updated the comment accordingly.
