### ISSUE TITLE
Will there be sections about label smoothing and finding wider minima in chapter 9?

### ISSUE THREAD

**Issue by rezunli96** [udlbook/udlbook#112]
Hello, thanks for this amazing book and I really enjoy reading it! One question: for section 9, according to the conclusion and notes, it seems like structurally there should be paragraphs about label smoothing and finding wider minima, but the version I have at hand seems to be missing these. Are they already discussed in somewhere else? Thanks in advance!

**Comment by udlbook** [comment]
Hey.  I'm glad you are enjoying it.  There are two paragraphs about label smoothing in section 9.3.4 at the bottom of P149 and top of P150.   There is a paragraph about wider minima just above this.

However, I think that you are right -- these connections could be more explicit.  I will try to improve this in the next edition.
