### ISSUE TITLE
Typo in Jupyter notebooks for Chapter 17

### ISSUE THREAD

**Issue by computbiolgeek** [udlbook/udlbook#113]
Hi Dr. Prince,  may I suggest the following two edits?
- In Notebook 17_1, change formatting of plot title from $Pr(x1,x2|z)$ to $Pr(x_{1},x_{2}|z)$. There are three of them in this notebook.
- In Notebook 17_3, there is a typo. I think $y=4$ in "which decreases rapidly as we move away from the position $y=4$" should be $y=3$.

**Comment by udlbook** [comment]
Thanks!  Fixed them all
