### ISSUE TITLE
Notebook 6.3 possible typo

### ISSUE THREAD

**Issue by AlekKCode** [udlbook/udlbook#114]
6.3 pertains to SGD. At the bottom of the notebook's implementation of SGD it says, "More properly, you should sample with replacement, but this will do for now". Shouldn't it say "More properly, you should sample WITHOUT replacement, but this will do for now"?

**Comment by udlbook** [comment]
Yes!  Thank you.  I have updated.  Can't believe that no-one spotted this before!
