### ISSUE TITLE
Typo in C.5.4 Distances between normal distributions

### ISSUE THREAD

**Issue by computbiolgeek** [udlbook/udlbook#115]
Hi Dr. Prince, it looks like there is a typo in Equation C.32. I believe you meant $\text{tr}\left[\Sigma_{2}^{-1}\Sigma_{1}\right]$ rather than $\text{tr}\left[\Sigma_{2}^{-1}\Sigma\right]$, i.e. there missed a subscript.

**Comment by udlbook** [comment]
Hey!  Thanks so much for writing.  Well spotted.  I have fixed this now and added your name to the acknowledgements.  It will be in the next online version and the next printing of the book (probably in about a year).  Let me know if you find anything else!

Simon
