### ISSUE TITLE
Better not to use `Pr(x)` in Chapter 16

### ISSUE THREAD

**Issue by isentropic** [udlbook/udlbook#116]
Dear Simon J.D. Prince first of all thanks a lot for your book, its truly great. I wanna report a minor notational misuse in chapter 16 with `Pr(x)`. You keep referring to it as probability, but it is probabilty density and usually referrred to as `f_X(x)`pdf. Usually if you mean `Pr(X=x)` it just zero as finding a continuous variable at a discrete location is impossible, instead it is usually defined in terms of a range with an integral `Pr(x2>X>x1) = int_(x1,x2) ...` if x1x2= +- infinity then the integral is exactly one for a single dim case. For example this resource uses much more conventional notation: https://www.math.umd.edu/~millson/teaching/STAT400fall18/handouts/changeofvariable.pdf

**Comment by isentropic** [comment]
Also problem 16.2 feels like it has a wrong calculation of the log derivative, but maybe im wrong

**Comment by udlbook** [comment]
Hi -- 

You are correct and I know this is true, but I don't like the notation $Pr(X=x)$ or f_X(x) as it seems overly formal and its rare that you actually have to distinguish between the random variable and the value that it takes.  So with some apologies (I actually discuss this in the notation section of the appendix).  Although it is imprecise, I don't think there's anywhere that it is genuinely confusing, so I'm okay with it (although I respect people like you who are upset by it too!) Also, it makes the notation compatible with my previous book.

With respect to problem 16.2, you are correct and it is fixed now.

Simon

**Comment by isentropic** [comment]
Thanks a lot for the response, my general gripe is not `Pr(X=x)` vs `Pr(x)` but that you actually mean is pdf with `Pr`, which is not the same as the probability itself. Granted I did not look through the first few chapters carefully, but I think it all starts in section 5.1 where you call it `Pr` not pdf. I feel you should add a footnote or something for the appendix perhaps at the begging of each chapter for selective readers like me. I was genuinely confused up to some point when reading one of the chapters only to realize that you mean pdf with `Pr`

Again thanks a ton for the book; it is great.

**Comment by udlbook** [comment]
Ahh... I see.   I think this notation is in wide use in ML and computer vision, but I can see now how it might be confusing.  I can't really make changes like this now, but I will note down and improve this in the second edition.
