### ISSUE TITLE
Appendix A Notation: Asymptotic notation: big-O notation explained as ‘tight’ upper bound

### ISSUE THREAD

**Issue by nehc0** [udlbook/udlbook#117]
In Appendix A Notation: Asymptotic notation, the big-O notation is explained as 'tight' upper bound, but the definition below is --- A function f[n] is O[g[n]] if there exists a constant c > 0 and integer n0 such that f[n] < c ∗ g[n] for all n > n0. This seems a definition of 'upper bound' rather than 'tight upper bound'.

**Comment by udlbook** [comment]
Hey,  

Thanks so much for writing.

I'm really not an expert on this (I never studied computer science!) but I think you are correct.  Also, it seems that there is some variation in how this is used in computer science which is probably why I was confused:

https://en.wikipedia.org/wiki/Big_O_notation#Use_in_computer_science

Anyway, I'm going to just remove the word "tight" which I think will make it correct.  Let me know if you disagree.

Simon

P.s. If you send me your full name to the e-mail on the book website, I'll happily add you to the acknowledgments at the start.
