### ISSUE TITLE
Small naming error in Ethics chapter

### ISSUE THREAD

**Issue by rasmi** [udlbook/udlbook#121]
The final sentence of Chapter 21 before the summary (page 434 in the December 24, 2023 version) reads:

> Leading work is published at both the Conference on Fairness, Accountability,
and Transparency (FAccT) and the Conference on AI and Society (AIES).

I think this should be:

> Leading work is published at both the Conference on Fairness, Accountability,
and Transparency (FAccT) and the **Conference on AI, Ethics, and Society (AIES)**.

Thank you for the lovely book!

**Comment by udlbook** [comment]
Well spotted!   Thanks.  It's fixed now and will be in the next online version and in the next printing of the physical book.   Happy to add your name to the acknowledgments if you send it to the e-mail address on the website.
