### ISSUE TITLE
Chapter 15 - DCGAN architecture. arctan instead of tanh?

### ISSUE THREAD

**Issue by ermiah** [udlbook/udlbook#124]
In Section 15.1.3, It states (both in the text and in the figure): 

> At the final layer, the 64×64×3 signal is passed through an **$arctan$** function to generate an image x∗ in the range [−1, 1].

The range of $arctan$ is $(-\pi/2, \pi/2)$. I think $arctan$ should be replaced with $tanh$ which has a range of [-1,1]. 

In the original paper of DCGAN, the activation function is also $tanh$: https://arxiv.org/abs/1511.06434. (page 3). 

Thank you for your phenomenal book. 

![image](https://github.com/udlbook/udlbook/assets/12352586/803a7c35-6d9e-4bb0-835d-79d2f87e23f4)

**Comment by udlbook** [comment]
Well spotted, Mohammad.  I've fixed that now (plus the figure, which also has a arctan in it).

**Comment by ermiah** [comment]
Amazing. Thank you Dr Prince.
