### ISSUE TITLE
Typographic error in Section 6.3.1

### ISSUE THREAD

**Issue by LawrenceNormie** [udlbook/udlbook#125]
> Nesterov accelerated momentum (figure 6.8) computes the gradients at
> **this** predicted point rather than at the current point:

Perhaps should be: "..gradient at **the** predicted point..."

**Comment by udlbook** [comment]
Hi Lawrence,  

Thanks for writing. I think I'm happy with "this" unless there is some particular way that it is confusing that I can't understand right now.

Feel free to reopen if you feel strongly about it!

Simon
