### ISSUE TITLE
Figure 9.5 a): description error

### ISSUE THREAD

**Issue by nehc0** [udlbook/udlbook#126]
In the description of Figure 9.5 a): "In each case, the number of iterations is 6000× the learning rate, so each solution has the opportunity to move the same distance". I guess it should be "6000 / the learning rate" rather than "6000 × the learning rate", as the distance = iteration × learning rate. Maybe I'm wrong.

**Comment by udlbook** [comment]
Thanks so much for noticing this.   You are correct. Sorry about that.  Will be fixed in next version/printing.    If you send your name to udlbookmail@gmail.com, I'll add you to the acknowledgments.
