### ISSUE TITLE
Typo error in Problem 19.7 [RL Chapter]

### ISSUE THREAD

**Issue by BalajiAI** [udlbook/udlbook#129]
In the solution for Problem 19.7, there is a typo.

![image](https://github.com/udlbook/udlbook/assets/77477328/3e00be5e-a538-4a62-8e01-06786864d8e5)

There should be a negative sign, instead of a positive sign. Since (a+b)^2 = a^2 + b^2 - 2ab.

**Comment by BalajiAI** [comment]
I guess, there is a typo in the question itself,
a' = a - c (b - mu_b) --> a' = a + c (b - mu_b)
With this new equation, we can get the expected results.

![image](https://github.com/udlbook/udlbook/assets/77477328/34bfebe0-67be-4951-b45b-8c5221217dd4)

**Comment by udlbook** [comment]
Hey! 

Thanks so much for writing.  You are correct about the typo in the answer, but the question is fine (it doesn't matter if we add or subtract c since we haven't estimated it yet) and the answer I gave it actually correct.  There must have been two problems cancelling each other out!
