### ISSUE TITLE
Typo in Solution for Problem 19.7

### ISSUE THREAD

**Issue by BalajiAI** [udlbook/udlbook#130]
This is a follow up of this github [issue](https://github.com/udlbook/udlbook/issues/129).

The formula for the correlation coefficient between two random variable is the following,

![a](https://cdn1.byjus.com/wp-content/uploads/2020/01/correlation-formula.png)

After that change, we need to use correlation coefficient squared for our needs. Like the following,

![image](https://github.com/udlbook/udlbook/assets/77477328/e6e24540-05dd-4381-8a0a-84f3fe1b297e)

Thanks!

**Comment by udlbook** [comment]
Thanks so much!   Should be fixed now.  I added a bit more to
the explanation of the answer as well.

Simon
