### ISSUE TITLE
mismatch between chapter numbering of figures and real numbering

### ISSUE THREAD

**Issue by psteinb** [udlbook/udlbook#132]
Dear @udlbook,

thanks a lot for this wonderful resource. I use the book extensively to teach Machine Learning in a Master's program. I discovered that the numbering scheme of the PDFFigures does not line up with what is in the book. For example, `PDFFigures/UDLChap17PDF.zip` contains all figures from the normalizing flows chapter. But in the latest version of the book, this is chapter 16. In a similar line of thought, `PDFFigures/UDLChap16PDF.zip` contains the figures of the VAE chapter. But this is chapter 17 in the latest version of the book.

Best,
Peter

PS. By latest version of the book, I refer to `UnderstandingDeepLearning_24_12_23_C.pdf`, i.e. https://github.com/udlbook/udlbook/releases/tag/v.1.18

**Comment by udlbook** [comment]
Thanks!   Well spotted.  Should be fixed now.
