### ISSUE TITLE
Minor issues with Notebook 8.1

### ISSUE THREAD

**Issue by girdeux31** [udlbook/udlbook#133]
Write absolute path to load mnist dataset, otherwise Google Colab does not find it and regenerates it: 

`data = mnist1d.data.get_dataset(args, path='/content/mnist1d_data.pkl' ...` 

`kaiming_uniform` is deprecated in favor of `kaiming_uniform_`, warning is shown.

`torch.nn.init.kaiming_uniform_(layer_in.weight)`

**Comment by udlbook** [comment]
Thanks Carles.  I. fixed the path issue (although the path was a bit different to what you suggested).   I think the kaiming_uniform thing is in your answer, not in the original notebook.

Let me know if you find any more.

**Comment by girdeux31** [comment]
True. I copied the `kaiming_uniform` from figure 7.8 on the book, so the comment applies there :).

**Comment by girdeux31** [comment]
I was just reading torch manual for kaiming initialization, just out of curiosity. Shouldn't it be more accurate to use `kaiming_normal_` instead of `kaiming_uniform_` to initialize weight parameters according to $\sigma^2_{\Omega} = \frac{2}{D_h}$? Though, I'm not sure what `fan_mode` is.

[https://pytorch.org/docs/stable/nn.init.html](https://pytorch.org/docs/stable/nn.init.html)

**Comment by udlbook** [comment]
Thanks Carles.  I have fixed this and I've added your name to the acknowledgements at the start of the book.  It will be in the next online version and next time the book is reprinted (probably in about a year). 

Let me know if you find anything else!

**Comment by girdeux31** [comment]
I am very thankful for it Simon!! :-)
Yes, I will.
