### ISSUE TITLE
Improved Code for Control Variates notebook

### ISSUE THREAD

**Issue by BalajiAI** [udlbook/udlbook#135]
Greetings,
For the context, Control variates is about constructing a new Random variable (c) which has the same Expectation of our old random variable (E[c] = E[a]), but with less variance compared to a. Here, c = a - b, where b is another Random variable which correlates with a.

In the control variates notebook, we're just trying to prove the above statement. Which is E[c] = E[a] and Var[c] <= Var[a].

But the solution notebook proves this statement indirectly via Central Limit Theorem. Which I'm afraid, most people will find it as confusing. So I'm suggesting a direct method to do so, which is also quite simple & easy. 
Pls see the below image for the direct method.

![image](https://github.com/udlbook/udlbook/assets/77477328/6a4d2b56-5698-4333-af0f-60afc364c5ca)

That's it!!

**Comment by udlbook** [comment]
Hi Balaji, 

Thanks for this.  You are correct, but the way I use it in the notebook is closely related to how it is used in the book (I think).  So I'm still thinking about what the right thing to do is.

Simon
