### ISSUE TITLE
small typos in Chapter 13(Graph)

### ISSUE THREAD

**Issue by shashashak** [udlbook/udlbook#136]
More specifically, in section 13.5.1 Training with batches, I thknk Large K inside the brackets should be replaced with small k.

Before: the parameters $\Phi = \\{  \beta_{K}, \Omega_K \\}_{k=0}^{K}$  

After: the parameters $\Phi = \\{  \beta_{k}, \Omega_k \\}_{k=0}^{K}$

version: 2023-12-24

**Comment by udlbook** [comment]
Thanks Jaekang,

I've fixed this now and will update in a few days.

Simon
