### ISSUE TITLE
Kindle phi in text looks different than phi in equations

### ISSUE THREAD

**Issue by mtaran** [udlbook/udlbook#142]
![Screenshot_20240121-191027.png](https://github.com/udlbook/udlbook/assets/65346/fe73c4f7-b616-4fe6-8492-d1ba8cdce159)

Per above, it's distracting/confusing that the phi symbols look different on Kindle. It's much nicer in the printed book where they're the same. Maybe the Kindle book supports over the air updates?

**Comment by udlbook** [comment]
Thanks for pointing this out.  I only make the online PDF and typeset the book.  The Kindle version was made by MIT press.  I have escalated this issue to them.
