### ISSUE TITLE
Improve the matrix calculus section

### ISSUE THREAD

**Issue by isentropic** [udlbook/udlbook#143]
Thanks again for the book, I had another issue earlier and you responded very well. Thanks for promptness

In section 7.4 you jump to matrix formulation of the backpropagation algo which is a natural progression of the scalar case. Though I suggest you warmup a little so that the reader could grasp what does it meant to take a derivetive with respect to a vector. For example this work https://www.doc.ic.ac.uk/~ahanda/referencepdfs/MatrixCalculus.pdf does it pretty well. And it builds the intuition why chain rules needs to "grow" to the right as opposite of conventional stacking to the "left". Maybe add a few paragraphs about the order of indices of vectors and the common misconception about how we take vector as the derived value.

**Comment by isentropic** [comment]
Maybe put such index by index intuition not directly in the text but as an additional part in B5. To me knowing explicitly how indices go was very educational ex. first two pages of [this same doc](https://www.doc.ic.ac.uk/~ahanda/referencepdfs/MatrixCalculus.pdf)

**Comment by udlbook** [comment]
Hi and thanks so much for pointing this out.  I agree that this could have been handled better.  It's hard to know how to do this properly.

I can only fix errors at this point and not rewrite things, but I have added this to my folder of suggestions for the second edition and I'll try to improve it when I write this.
