### ISSUE TITLE
Minor Typo(?) Fig 9.5

### ISSUE THREAD

**Issue by davidquarel** [udlbook/udlbook#147]
In figure 9.5 (attached) the x-axis of the plot is "hidden figure size", but the plot is of a loss curve over time.
![Screenshot_2024-01-30-09-17-03-202_org readera](https://github.com/udlbook/udlbook/assets/7093339/7439f202-fccb-45fc-9c17-5b5d00c28ab0)

**Comment by udlbook** [comment]
Hi David, 

Thanks for bringing this up and apologies for the slow response.  I am seriously behind with everything.   

Actually, this is not a mistake though.  Each point on the curve represents a different neural network with different capacities.  The performance is shown at the end of training. It actually says how many training iterations there were in the legend.

I can see why you identified this though as it is a bit of an unusual way to present it.  I was really trying to show how robust these effects are, regardless of the training run and regardless of the capacity.

Simon
