### ISSUE TITLE
Section 12.7.2 reference to 'all upward angled arrows'

### ISSUE THREAD

**Issue by mathursuhas** [udlbook/udlbook#148]
First, thanks for a very well written book - kudos to you on the accomplishment!

Section 12.7.2 (Masked Self Attention) specifies "Hence, the problem can be resolved by ensuring that the attention to the answer and the right context is zero". But then goes on to say: 
"The effect is to make the weight of all the upward-angled arrows in figure 12.1 zero." 
Should this be:
"The effect is to make the weight of all the upward-angled AND HORIZONTAL arrows in figure 12.1 zero." 
?
If yes, then maybe Figure 12.12 would also need updating to remove horizontal links in the orange self attention block. 
If not, then the two statements above seem contradictory.

**Comment by mathursuhas** [comment]
Actually, Fig 12.12 looks fine. I realize now, after a closer look, that for each token position in the input, you are not trying to predict that token but the next token on the far right of the figure. 
But the two sentences I quoted above still seem potentially conflicting.

**Comment by udlbook** [comment]
Hi!

Thanks so much for these messages.   I was just about to look into this, and you saved me the trouble!  Yes.  I think it's fine for exactly the reason that you state.

But that doesn't mean that there are not other mistakes in the book, so please message me again if you find anything amiss. I would really like to make it perfect.

Simon
