### ISSUE TITLE
Eq. 6.12

### ISSUE THREAD

**Issue by nickzooot** [udlbook/udlbook#149]
Hi!

I am not sure, but I think that the step $[\phi_t -\alpha \cdot m_t]$ in $l_i$ should be changed to $[\phi_t -\alpha \beta \cdot m_t]$. It seems logic if to write the full optimization step  in one equation:
$$\phi_{t+1} = \phi_t - \alpha \beta \cdot m_t - \alpha (1-\beta) \cdot \sum_{i \in B_t}\frac{ \partial{l_i[\phi_t -\alpha \beta \cdot m_t]}}{\partial{\phi}}$$

**Comment by udlbook** [comment]
Hi Nick, 

Thanks so much for getting in touch.   I have pondered this, and I'm not sure that I agree.   If we did this in one step, then $m_{t}$ would never be updated, and this is important.

It's possible that I have misunderstood though, so feel free to reopen this issue if you disagree.

Simon

**Comment by nickzooot** [comment]
I wrote it in one step in order to show why I think that in the update of $m_t$ there should be $[\phi_t -\alpha \beta \cdot m_t]$ instead of $[\phi_t -\alpha  \cdot m_t]$. That is so because the main idea of Nesterov momentum is to make a correction after $\phi_t - \alpha \beta \cdot m_t$

**Comment by udlbook** [comment]
Ah... I see what you mean now, and I think that you are correct (although probably doesn't make much difference in practice).  I have fixed this in the latest version.   If you send your full name to the address on the front of the online version, then I'll add you to the acknowledgements.

Thank you very much!

Simon

**Comment by nickzooot** [comment]
My full name is Nikita Panin.

Thanks for your book! Can't wait to read the second edition of a book, hopefully, with even more new materials)

Best regards,
Nick!
