### ISSUE TITLE
Citations are not well formatted at page 205 (January 23, 2023 release)

### ISSUE THREAD

**Issue by alessandro-gentilini** [udlbook/udlbook#15]
At page 205 citations are not well formatted, it seems there is some problem with the LaTeX commands, see this screenshot:
![image](https://user-images.githubusercontent.com/2438459/214390417-6d516f59-ef60-4054-88b4-4dd32be82c35.png)

**Comment by udlbook** [comment]
Thanks Alessandro.  I've been reformatting all the references, so there might be more problems.  Hopefully not.  New version should be posted shortly, with your name added to the acknolwedgements.

Really appreciate it.  Let me know if you find any more.
