### ISSUE TITLE
Fig 9.9

### ISSUE THREAD

**Issue by mathursuhas** [udlbook/udlbook#153]
Fig 9.9(b)'s title is 'Turn off hidden unit 8'. Its not clear what 'unit 8' refers to. 

I think this figure along with the body of text explaining this example are probably making a reference to an actual neural net, but I can't seem to find a reference to another figure for that network. Is it Fig 9.8?

**Comment by udlbook** [comment]
Ah... well spotted.  It's actually the model from figure 8.4.  I have added some clarification to the legend which will appear in the next online version and when the book is reprinted.   Thank you so much!   If you send your full name to the address on the front of the online version, then I'd be happy to add it to the acknowledgements.

Simon
