### ISSUE TITLE
Typo in Sec 11.3?

### ISSUE THREAD

**Issue by mathursuhas** [udlbook/udlbook#154]
"Without careful initialization, the magnitudes of the intermediate values during the forward pass
of backpropagation can increase or decrease exponentially. "

-->

"Without careful initialization, the magnitudes of the intermediate values during the forward pass
**or** backpropagation can increase or decrease exponentially. "

?

**Comment by udlbook** [comment]
Agree that this is a bit ugly, but not technically wrong (which is presumably why you closed it).  I'm going to file this to improve in the second edition.  Thanks!
