### ISSUE TITLE
Problem 2.3 and mentioning Model-II regression

### ISSUE THREAD

**Issue by chrarnold** [udlbook/udlbook#155]
It is a great book, and we are currently running a book reading club that goes through the content chapter by chapter.

While doing Problem 2.3 and reading up further concepts online, I realized that so-called Model-II regressions could be mentioned either as part of the problem description or as part of the available solution to highlight that (1) existing work for this already exists and (2) it seems still easier than generative problems in cases for which also x is suspected to / known to contain measurement error.

Or a reference to this somewhere may be helpful, because the problem makes this distinction (optimizing the vertical vs horizontal distance) very apparent.

**Comment by udlbook** [comment]
Hi Christian, 

Thanks so much for your kind words and for this comment.  I actually didn't know that this type of regression had a name, so I learned something here!  I'm not really allowed to make changes to the book except to fix mistakes, so I added this to the answer booklet.  I've also added your name to the acknowledgements.  You'll see these changes when  I next update.  I've also filed this away to update the main text when I write a second edition.

Thanks again!

Simon

P.s. If you had a moment, then an Amazon review would be much appreciated.  If I want to write a second edition, then I have to sell a few copies...  No worries if you don't have time though.
