### ISSUE TITLE
Example solution for problem 3.4  incorrect in UDL_Answer_Booklet_Students

### ISSUE THREAD

**Issue by chrarnold** [udlbook/udlbook#156]
In the January 4th version of the (selected) answers that I have, Figure 3.1 for Problem 3.4 seems incorrect: While the shape of the function in all 4 sections seems correct, the curve is shifted upwards: It should be below 0 (-0.23) for the first section, for example, due to the the fact that Φ0 = -0.23 according to the parameters given in Problem 3.8, and correspondingly adjusted downwards for the other sections as well.

**Comment by udlbook** [comment]
Hi and thanks so much for pointing this out.   You are completely correct.  Actually, when I went back to the original graphic file, it was correct, so I obviously fixed this at some point but forgot to update the document.  Anyway, it's done now, and I've also added some extra explanation to the answer.

Thanks for taking the time to point this out.  Let me know if you find anything else!
