### ISSUE TITLE
"Evidence" in Section 17.3.3

### ISSUE THREAD

**Issue by mathursuhas** [udlbook/udlbook#157]
I found this potentially a bit conflicting: 

"(ELBO) It gets this name because Pr(x|ϕ) is called the evidence in the context of Bayes’ rule (equation 17.19)."

However, earlier on that page (equation 17.14), log[Pr(x|ϕ)] is called the log of the **likelihood**. Pr(x|ϕ) does look like the likelihood. Under Equation 17.19 too the term Pr(x|ϕ) in the denominator is referred to as the 'data likelihood'. 

Technically, I believe Pr(x) is called the evidence? 

Not sure if this comment should go into an errata or the pile for future improvements, but I thought I'd leave the above comment here nonetheless.

**Comment by udlbook** [comment]
Hi Suhas,

Thanks for writing. I don't think the first two terms are contradictory.
The term in Equation 17.14 is the likelihood of the data x given parameters
phi (no latent variables z here).  However, in the context of Bayes rule,
it is the evidence for x in the Bayes' rule calculation relating x and z
(and for fixed phi).
I agree though that this is confusing, and I also don't like the forward
reference. I didn't think there were any forward references in the book. I
think I rearranged the text at some point and it wound up this way.

I can't really make big changes at this point, but I've flagged this for
improvement in a future edition.

Your second point is absolutely correct though.  This should be termed the
evidence and I have fixed this.

Thank you so much for your help.  This is EXACTLY the kind of thing I care
about.  Let me know if you spot anything else.

Simon
