### ISSUE TITLE
Example solution for Problem 4.11

### ISSUE THREAD

**Issue by chrarnold** [udlbook/udlbook#159]
Hi, I am having trouble understanding the example solution for the number of linear regions for the Deep Network, and I believe the solution of 7776 is either wrong or the formula 4.17 is wrong.

When I plug-in the numbers, I have (5/1 + 1)^(1 * (10-1)) = 6^9 for the first time and (1 + 5) = 6 for the second term.
However, in your provided 7776 solution, I think that corresponds to 1296 * 6 = 7776, and the first term here is 6^4. Thus, just the exponent differs: 9 in my solution, 4 in yours, where the differences comes from here? Is it possible you accidentally replaced the K=10 with D=5?

In addition, it was (to me at least) not immediately clear that "scalar" input and output refers here to D_i = D_o = 1. Maybe this can be made more explicit in the problem description.

**Comment by udlbook** [comment]
Thanks so much, Christian.  You are absolutely right in your diagnosis.  I
do apologize for the confusion.  I have fixed this and will update on the
website.

Simon
