### ISSUE TITLE
Formula (16.25) missing a scaling factor

### ISSUE THREAD

**Issue by nehc0** [udlbook/udlbook#161]
Formula (16.25) missing a scaling factor “1/I”, compared within formula (16.26)

**Comment by udlbook** [comment]
Hi - 

Thanks so much!  You are (of course correct).  Without the normalization it's not even a probability distribution.  I've fixed this now and it will be incorporated in the next update.   If you send your full name to the address on the front of the PDF, I will add your name to the acknowledgements!

Simon
