### ISSUE TITLE
Improve Problem 5.1 wording for accuracy and concept exploration

### ISSUE THREAD

**Issue by iftikharramnandan** [udlbook/udlbook#165]
I thought it incorrect to have z = +-∞, as we don't substitute z = ∞ into the equation, as in the case of z = 0. Moreover, infinity is not a numerical input we can plug in.  It's more correct to think about how a function behaves as z gets larger and larger (approaches infinity) and whether that behavior leads to a specific limit.

The question says when z = -∞ and when z = ∞, but shouldn't it say when z approaches infinity or negative infinity? I do see the point of z=∞ or z=−∞ being used for the sake of simplicity or to make the material more accessible to readers who might not be familiar with limit notation. Moreover, I do understand this book is all about explaining the underlying ideas of deep learning and less so about being terribly theoretical. So, I see how my first idea of `lim_(z →-∞) sig[z] = 0 
lim_(z → ∞) sig[z] = 1 ` while being more precise/rigorous doesn't necessarily need to be used given the goal of the book and the goal of the problem =. However, I do think that not everyone will understand the implied limit process; so, perhaps some middle ground between z=∞ or z=−∞  and lim_(z → -∞) of sigmoid of z = 0 and lim_(z→ ∞) of sigmoid of z = 1 could be found that helps people understand that there's an implied limit process needed in properly understanding the solution to the problem.

After solving the problem, I thought about the goal, which I would conceptualize as: showing the logistic sigmoid function is useful for mapping real numbers to the range [0, 1], which is particularly helpful when working with probabilities, such as in binary classification problems. 

I wanted to adjust the problem to keep the goal in mind, but also move away from language of z = +-∞ and more towards language about z approaching +-∞.  And so, with all of this in mind, here's what I came up with: 

Proposed question change:
Explore how the logistic sigmoid function `sig[z]=1 / (1 + exp(-z))` transitions as z approaches −∞ and ∞, and demonstrate how this allows sig[z] to effectively maps any real number z to a value within the [0, 1] range. Discuss the implications of sig[z]'s behavior for modeling probabilities in binary classification contexts.

**Comment by udlbook** [comment]
Hi,

Thanks so much for writing and apologies for the long delay;  I've been on
vacation.

I agree with your point and I've reworded the question to make it slightly
more precise.   I'm not really allowed to make changes that aren't
mistakes, so I haven't used your full proposed question change, but I'm
going to store this e-mail and put it in when I write a second edition.

If you send your full name to the address on the front of the PDF, I'd be
happy to add your name to the acknowledgements.   Let me know if you have
any further suggestions.

Simon
