### ISSUE TITLE
SVG resources of Chap17 and Chapt16 have been mistakenly swapped.

### ISSUE THREAD

**Issue by careywyr** [udlbook/udlbook#167]
![image](https://github.com/udlbook/udlbook/assets/17082044/4f36dde5-c43e-4f8f-88d1-b5342351d38e)
![image](https://github.com/udlbook/udlbook/assets/17082044/52586417-0185-4525-86a3-ed6093cd31f6)

**Comment by udlbook** [comment]
Hi, 

Thanks so much.  I finally got around to fixing this.  Let me know if you find anything else.

Simon
