### ISSUE TITLE
Typo in Rule 2 of Rules for manipulating expectations

### ISSUE THREAD

**Issue by ggldnl** [udlbook/udlbook#168]
In Appendix C, Probability, Rules for manipulating expectations, Rule 2:

$\mathop{\mathbb{E}}[k \cdot [x]] = \int k \cdot f[x] Pr(x) dx$ ...

the part to the left of the first equal sign should be $\mathop{\mathbb{E}}[k \cdot f[x]]$

**Comment by udlbook** [comment]
Thanks so much!   Will be fixed in the next version.  If you send me an e-mail to the address on the front of the PDF, I'd be happy to add your name to the acknowledgements.
