### ISSUE TITLE
Missing citation (version 2023-01-24)

### ISSUE THREAD

**Issue by salarian** [udlbook/udlbook#17]
Page 138, section 9.2, Implicit regularization: the first sentence talks about "An intriguing recent finding..." which calls for a citation.

**Comment by udlbook** [comment]
Actually, this is by design.  There are a couple of references in the main body of the convolution chapter, but I plan on removing them and just having all the references at the end.  It's a controversial decision, I suppose, but I think they just distract from the main ideas.

**Comment by asalaria-cisco** [comment]
Thanks a lot for your comment. Indeed, after spending more time reading the book, I came to realize this is a deliberate decision. Nonetheless, as long as the references are there at the end of chapter, I guess all is well.
