### ISSUE TITLE
12.5 Formulation [typo]

### ISSUE THREAD

**Issue by j0m0k0** [udlbook/udlbook#171]
I think in the second part that you have expanded the softmax function, there should be a dot '.' instead of comma ',' in the denominator.

**Comment by udlbook** [comment]
Hi, 

Thanks so much for writing.  I think this is okay.  The comma isn't part of the equation, but part of the sentence, which continues "so for each x_n...".

Feel free to reopen if I have misunderstood something.   

Let me know if you find anything else.  There are still plenty of things in there that need fixing, and I do care about tiny details like this.

Simon
