### ISSUE TITLE
Typographical  fix: Pr should be upright roman

### ISSUE THREAD

**Issue by djmarti** [udlbook/udlbook#177]
Thanks for this super-interesting book.

I have a suggestion to make, which seems rather minor but it would fix a glitch that is rather prominent to typography nerds like me. The abbreviation "Pr" for probability appears in math mode as italics, which may be  interepreted as the product of P and r. To avoid this confusion, a compound symbol like this is tradionally set as upright roman (see, e.g., Appendix A of the [AMS  Style Guide](https://www.ams.org/arc/styleguide/index.html)). My suggestion is to use the amsmath package and declare

```
\DeclareMathOperator{\Pr}{Pr}
```
in the preamble (see  §5.1 of [amsmath](https://ctan.org/pkg/amsmath?lang=en)'s user's guide), and then use `\Pr` instead of `Pr` throughout the text.

The other option, of course, is to just use `p` to represent probability, but I guess you'd rather go with the more explicit `Pr`.

Thanks again for your attention.

**Comment by udlbook** [comment]
Hi Dani,

I 100% agree with you.  I did it this way, so that it was compatible with
my previous book, but honestly, I wish that I had just changed to p().  I'm
a bit scared to make this change in the current version as there would be a
very large number of changes and it might introduce some errors.  However,
I have flagged this to change in the second edition which I will write in a
couple of years.

Simon

**Comment by djmarti** [comment]
Thanks Simon. Fair enough, that would represent quite a few replacements in
the book and I understand you don't want to risk it for now (especially
given that the book is becoming a sensation!).

Thanks again for writing this book. It is nicely written and covers a lot
of recent material. It is definitely a great reference.

El dc., 10 d’abr. 2024, 12:50, udlbook ***@***.***> va
escriure:

> Hi Dani,
>
> I 100% agree with you. I did it this way, so that it was compatible with
> my previous book, but honestly, I wish that I had just changed to p(). I'm
> a bit scared to make this change in the current version as there would be
> a
> very large number of changes and it might introduce some errors. However,
> I have flagged this to change in the second edition which I will write in
> a
> couple of years.
>
> Simon
>
