### ISSUE TITLE
Typo in equation 13.22

### ISSUE THREAD

**Issue by valeriodiste** [udlbook/udlbook#179]
In the UDL book (PDF version of 03 April 2024) equation **13.22** (for Chapter 13 on Graph Neural Networks) is currently:

$H'_k = \beta_k I^T + \Omega_k H.$

but shoud be:

$H'_k = \beta_k I^T + \Omega_k H_k.$

**Comment by udlbook** [comment]
Thanks so much.  It's fixed and will be in the next online version and sorted out in the next printing (probably in about six months).  If you send your name to the e-mail address on the front of PDF,  I'd be really happy to add your name to the acknowledgements.   

Please let me know if you find anything else!
