### ISSUE TITLE
About Algorithm 18.1: Diffusion model training

### ISSUE THREAD

**Issue by kli-casia** [udlbook/udlbook#18]
Great book!
I have a question about Algorithm 18.1
I can not find the first part of Equation 18.37 in Algorithm 18.1
Thank you!

![image](https://user-images.githubusercontent.com/13194870/215638843-5d8ca89b-84c9-482c-89c9-78807a1002f3.png)
![image](https://user-images.githubusercontent.com/13194870/215638887-6558d8b6-9d5d-4b32-8616-828a09bc6e61.png)

**Comment by udlbook** [comment]
Hi -- I think it is actually there -- the negative log of the normal gives a least squares formulation that is the same as the other terms.  However, I agree that this could be made clearer.  I've put a TODO in my Latex file to improve this when I come back to this chapter.

Thanks for your help!  I have added your name to the acknowledgements!

Simon
