### ISSUE TITLE
Error in Notebook 7_3_Initialization.ipynb

### ISSUE THREAD

**Issue by zeeskore** [udlbook/udlbook#181]
In the notebook 7_3_Initialization.ipynb,  the function **def backward_pass()**, the line:

  Retrieve number of layers
  K = all_weights

throws a TypeError: can only concatenate list (not "int") to list.

I think this should be   K = len(all_weights)-1

Nice book, enjoyed reading it so far.

**Comment by udlbook** [comment]
Fixed!  Sorry, I think I introduced this problem when I fixed another one.   Thanks so much for your help.
