### ISSUE TITLE
Chapter 11 Resnet section 11.3 exploding gradients in resnet page 192 - why is the branch uncorrelated?

### ISSUE THREAD

**Issue by total-expectation** [udlbook/udlbook#182]
Hi, 

I don't fully understand why the output from skip connection and the output from the block in a resnet block are uncorrelated. Is it simply because the non-linearity introduced in the block breaks the correlation between the two?

Thanks in advance!

**Comment by udlbook** [comment]
Hi -- good question!  It's not the nonlinearity.  That would set the
negative values all to zero, but any correlation in the positive values
would be preserved -- think about an oriented Gaussian centered on the
origin where each axis represents one variable.  The ReLU just maps
everything except the top right quadrant to the origin, and any correlation
in the top right quadrant remains.

What causes it is the normally distributed random weights that multiply
this output.  They multiply the random variables by a random positive or
negative value, and so on average they no longer correlate with each
other.

Hope this helps,

Simon

P.s. I have stored this message in my "todo" list for the second edition.
Maybe I can draw a picture that makes this more clear.

**Comment by total-expectation** [comment]
Thanks for the answer! I think I understand, but sure any clarifications with pictures would be helpful for other readers as well! 

I will close this now, because I'm happy with the answer.
