### ISSUE TITLE
Small typo - C.5.4 Distances between normal distributions page 461

### ISSUE THREAD

**Issue by total-expectation** [udlbook/udlbook#184]
Hi,

In this section of the appendix in the book you describe the KL-divergence between two multivariate gaussian distributions.

![image](https://github.com/udlbook/udlbook/assets/136351629/5b40dced-ddd8-4142-872e-ac933ca6776c)

As you can see the log is applied to the entire expression in the book.
However, looking at the relation on [wikipedia](https://en.wikipedia.org/wiki/Multivariate_normal_distribution#Kullback%E2%80%93Leibler_divergence) for instance, it can be seen that the log or ln is only applied on the $\frac{|\sum_{2}|}{|\sum_{1}|}$ term.

![image](https://github.com/udlbook/udlbook/assets/136351629/60ab4686-6755-4d27-96ac-5f86c841e12d)

I have an older version of the book, so I looked at the newest version on the website (01 may 2024) and noticed that the typo persists. I hope I haven't misunderstood something, but if it is a typo hopefully this can be fixed soon.

Thanks in advance!

**Comment by udlbook** [comment]
Thanks so much for pointing this out.   I've fixed it now.   I'm grateful for your continued support!  Let me know if you find more.
