### ISSUE TITLE
Wrong colors in text of fig 8.5b p. 119

### ISSUE THREAD

**Issue by LeonardoViotti** [udlbook/udlbook#19]
In fig _8.5 Sources of test error_, subplot _b)_ text says:

"b) Bias. Even with the best possible parameters, the three-region model (brown line) cannot fit the true function (cyan line) exactly. (...) "

To match the colors in the figure it should say:

"b) Bias. Even with the best possible parameters, the three-region model (cyan line) cannot fit the true function (black line) exactly."

**Comment by udlbook** [comment]
Thanks Leonardo!  I've fixed this and added your name to the acknowledgements (as Leonardo Viotti -- let me know if this isn't right).  This monster is super-hard to proof and I really appreciate your help.  Let me know if find any more.
