### ISSUE TITLE
Typo in equation 7.22

### ISSUE THREAD

**Issue by dovzh** [udlbook/udlbook#191]
![formula_7 22](https://github.com/udlbook/udlbook/assets/48121966/b6ac5beb-61e7-4d24-89da-b51a4f8dff8c)

**Comment by udlbook** [comment]
Hi --  I think you are suggesting that these should be switched around, but actually it is correct.  The derivative we are calculating needs to be the same size as Omega_k and so it's number of columns should be the same as the number of rows in h_k (which is multiplied by Omega_k.  Matrix calculus is super-awkward;  I wouldn't get too hung up on this.
