### ISSUE TITLE
Inconsistent time index usage for the reward in equation (19.30) and (19.31)

### ISSUE THREAD

**Issue by zhengyunqq** [udlbook/udlbook#197]
In the 05-27 version,

The time index for the reward $r_t$ is started from 2 defined at the begining of the chapter 19. However in equation (19.30) and (19.31) the time index for reward $r_t$ is started from 1.  I think (19.30) should be: 
$\sum\limits_{t=2}^{T+1} r_{it} = \sum\limits_{k=2}^{t}r_{ik} + \sum\limits_{k=t+1}^{T+1}r_{ik}$. 

And the rightmost term of (19.31) should be  $\sum\limits_{k=t+1}^{T+1}r_{ik}$. Sum in (19.32) should be $\sum\limits_{k=t+1}^{T+1}$

Furthermore, in equation (19.39), I think the rightmost term should be changed to $\sum\limits_{j=t+1}^{T+1}r_{ij}$

**Comment by udlbook** [comment]
Hi Zhengyun,

Yes, you are correct.  I actually fixed it (and in a few other equations)
by changing to $r_i,k+1$ but the idea is the same.

Thank you so much for your help.  If you send your full name to the e-mail
address on the front of the pdf, I'd be happy to add your name to
the acknowledgements.  Please let me know if you find anything else!

Simon
