### ISSUE TITLE
Incorrect Function Call in notebook

### ISSUE THREAD

**Issue by dokudo91** [udlbook/udlbook#199]
In the update_generator function of [15_1_GAN_Toy_Example.ipynb](https://github.com/udlbook/udlbook/blob/main/Notebooks/Chap15/15_1_GAN_Toy_Example.ipynb?short_path=4f18380#L342), the function call compute_generator_gradient(x_real, x_syn, phi0, phi1) appears to be incorrect. Based on the context, it should be compute_generator_gradient(z, theta, phi0, phi1).

**Comment by udlbook** [comment]
Thanks so much.  I have fixed this now.  Let me know if you find anything
else!

Simon
