### ISSUE TITLE
Figure 3.8

### ISSUE THREAD

**Issue by siavashk** [udlbook/udlbook#2]
I found the explanation for Figure 3.8 to be lacking. I understand that each image in Figure 3.8 a) to e) corresponds to one activation unti, but I do not understand what the gray lines mean and what does the brown gradient represent.

An explanation along the following lines would benefit the reader: "For example, in Figure 3.8 a), a gray line is the intersection (?) of one of the hyperplane parameterized with (\Phi_0, \Phi_1, \Phi_2) with the (x_1, x_2) plane. The color of the image represents the value of the resulting linear combination of parameters and inputs with warmer colors corresponding to more positive values."

**Comment by udlbook** [comment]
Thanks Siavash,

It's really helpful to see what people find confusing.  I'll definitely
update the legend.
