### ISSUE TITLE
P. 279: GAN loss parameters

### ISSUE THREAD

**Issue by ckang244** [udlbook/udlbook#20]
```Equation 15.4 is a more complex loss function than we have seen before; the discriminator parameters φ are manipulated to minimize the loss function and the generative parameters φ are manipulated to maximize the loss function. ```
I think the second φ should be θ, if my understanding is correct.

**Comment by udlbook** [comment]
Thanks Chris.  I've fixed it and added your name to the acknowledgements.   Incredibly helpful!  Let me know if you find any more.
