### ISSUE TITLE
Chapter 18.2 Encoder (forward process) equation 18.1 - Clarification on scaling down factor

### ISSUE THREAD

**Issue by total-expectation** [udlbook/udlbook#212]
Hi,

Not so much an issue as a question about clarification. In the paragraph for eqauation (18.1) it says that the first term in 

$$z_t = \sqrt{1 - \beta_t}z_{t-1} + \sqrt{\beta_t}\epsilon_t$$

has an attenuating effect on the data and any noise added to it so far. I'm wondering what is the purpose of scaling it down? Does it have something to do with variance preservation, where you want the variance to be at a similar scale between each time step, so that it doesn't explode when we go from t=1 to t=T? If this is true, is there a proof of this? I can't seem to think of how you would prove this.
OR is this perhaps simply because we want to make the mean slowly move towards zero when we reach timestep T, and the scheduler figures that out somehow for us?

Also a follow-up question is how does this magical scheduler figure out the scalings for us? What is the mathematical framework for this?

Thanks in advance!

**Comment by udlbook** [comment]
Hi --

Thanks for writing and apologies for taking so long to reply.  Yes, you are
basically correct, it means the variance will eventually become the
identity.  Indeed if it starts as being the identity, it will remain that
way.  This is actually investigated in problem 18.1.  I attach the answer
here.

Simon

**Comment by total-expectation** [comment]
Thanks for the answer and no need to apologise, it's already appreciated that you spend any time outside your working time to answer these questions.

Sorry for being slow, but after thinking a bit more about the forward process in general I have one follow-up question related to this. 

My understanding was that the variance of latent $z_t$ is precisely $1 - \alpha_t$ (because $z_t \sim \mathcal{N}(\sqrt{\alpha_t}x, (1-\alpha_t)I)$ that changes throughout the timesteps due to the scheduler and that we are adding noise each time? Despite this, why does the variance seem different when we take the variance directly like $V[z_t] = \alpha_tV[x] + (1-\alpha_t)V[\epsilon] = \alpha_tV[x] + (1-\alpha_t)I$, where now we need to know what $V[x]$ is to know the variance of the latent $z_t$. Perhaps my understanding is wrong, because $V[x]$ would have to be zero in order to align with my understanding of what the variance of the latent at time t is, which doesn't seem correct, because even with scaling in the preprocessing step we don't usually transform data to have zero variance.

Thanks in advance!

**Comment by udlbook** [comment]
I think what is confusing you is the difference between a concrete input
$x$ (which has variance V[x]=zero) and a distribution over possible inputs
$Pr(x)$ which has some variance $V[x]$.  These correspond to the first and
second cases that you mention.

Simon
