### ISSUE TITLE
3.1.1 Neural network intuition

### ISSUE THREAD

**Issue by jinto** [udlbook/udlbook#214]
"The slope of each linear region is determined by (i) the original slopes θ•1 of the active inputs for this region and (ii) the weights ϕ• that were subsequently applied. For example, the slope in the shaded region (see problem 3.3) is θ11ϕ1 + θ31ϕ3, where the first term is the slope in panel (g) and the second term is the slope in panel (i)."

In this paragraph, (i) is used with two different meanings. How about changing (i) and (ii) to 'first' and 'second' respectively?

**Comment by udlbook** [comment]
Hi Jay,

Thanks so much for taking the time to point this out.  I agree.  In the
end, I just cut out the (i) and (ii) altogether.  I've added your name to
the acknowledgements and you'll see this next time I update the online
version and when the book is reprinted (probably in about a year).   Let me
know if you find anything else!

Simon
