### ISSUE TITLE
Typo in Equation C.27

### ISSUE THREAD

**Issue by ronaldpan** [udlbook/udlbook#220]
It should be Pr(x, y, z) = Pr(x)Pr(y|x)Pr(z|x,y).

**Comment by udlbook** [comment]
Hi!

Thanks so much for taking the time to point this out.  This is not actually
a mistake, but I admit that it's a bit ambiguous.  I was trying to say
that *for
this particular distribution*, the joint distribution factors in this way.
 This all relates to graphical models and how some probability
distribution can be factored in non-general ways.   If you don't know about
that and want to learn more, there are details in Chapter 10 of my previous
book:  https://udlbook.github.io/cvbook/

I've changed the wording a bit now so this is more clear.  You'll see the
change when I next update the online version.   If you send your full name
to the address on the front of the PDF, I'd be happy to add you to the
acknowledgements.

Please let me know if you find anything else.  All of these tiny things
really matter to me!

Simon
