### ISSUE TITLE
notation of parametric distribution

### ISSUE THREAD

**Issue by ronaldpan** [udlbook/udlbook#222]
In UDL, Pr(y|θ) denotes a parametric distribution, not  a conditional probability. In other books, a parametric distribution is denoted by Pr(y;θ).  This should be explained and emphasized in the book.

**Comment by udlbook** [comment]
Ah... well, this is true if you are a frequentist, but if you are a
Bayesian, then the parameters \theta are also considered as quantities that
vary and perhaps have a probability distribution over them and it's
commonly written this way (think of Bayes's rule to compute the MAP
solution).

So I think I'm okay with the current notation, but perhaps I'll add
something about this in the notation section in the second edition.

Simon
