### ISSUE TITLE
add a common dependency file requirements.txt to install all dependencies at one go?

### ISSUE THREAD

**Issue by muddlebee** [udlbook/udlbook#225]
like here I added https://github.com/muddlebee/udlbook/blob/dev/Notebooks/requirements.txt

torch
scipy
numpy
matplotlib
sklearn
git+https://github.com/greydanus/mnist1d

and add a common path for **mnist1d** across all codes?

**Comment by muddlebee** [comment]
@udlbook does it make sense above? shall I send a PR?

**Comment by udlbook** [comment]
Hey!   Thanks for getting in touch and apologies for the slow response.  It does make sense, but I don't really see the advantage.  I think it's probably a good thing that the requirements are explicit and at the top of each file?

**Comment by muddlebee** [comment]
yeah makes sense for folks who want to run individual google collab notebooks..

but a common way to install all dependencies at one go, would make it little convenient for newbies?
also I have observed, mnist1d is used across many code examples and it downloads everytime :( maybe a common folder dataset everytime it can refer? for non collab users.

**Comment by udlbook** [comment]
Ahh... of course you are right, but I don't really want different versions
for colab and non-colab people.  I think it's best as it is.

**Comment by muddlebee** [comment]
makes sense. thank you for your reply. closing this :) 
also much thanks to you my journey in deep learning has been quite smooth.. the intuitive teachings and code/visualizations are just top notch. Appreciate the effort you have put into this 🙏
