### ISSUE TITLE
B.1 Functions - surjection 

### ISSUE THREAD

**Issue by ronaldpan** [udlbook/udlbook#226]
A surjection is a function where every element in the second set receives a mapping from the first.
**(but there may be elements of the first set that are not mapped)**  
It should be "but there may be more elements of the first set that are mapped to the same element of the second set."
For a function defining a mapping from a set to another set, every element of the first set should be mapped to an element of the second set.

**Comment by udlbook** [comment]
Oh, how embarrassing.  Of course you are correct.  It's the first addition
to the "major errors" section for a while.

Thanks so much once again!

Simon
