### ISSUE TITLE
Access forbidden to gz files on yann.lecun.com for notebook 10.5

### ISSUE THREAD

**Issue by goliath49** [udlbook/udlbook#229]
The access to https://yann.lecun.com/exdb/mnist/ webpage is ok, but clicking on e.g. https://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz doesn't work.

**Comment by udlbook** [comment]
Hi,

Apologies for this.  Something must have changed.  There's seems to be a
mirror of these files at:

https://github.com/cvdfoundation/mnist?tab=readme-ov-file

I'll update the notebook to reflect this.

Thanks,

Simon

**Comment by udlbook** [comment]
BTW, sorry about the very long delay in replying.  I just got back from vacation!

**Comment by goliath49** [comment]
Thanks for your feedback, and again, congrats for this amazing book & associated notebook!

**Comment by goliath49** [comment]
Just a small constructive comment about the book: maybe a small chapter on CNN/GRU could be valuable for people interested in DNN for audio? Maybe you have advices on where to find info (same level as in your book) about this in the litterature?

**Comment by udlbook** [comment]
I think you probably mean RNN and GRU?   Yes, I slightly regret not adding
that to the first edition, and I definitely plan to add it for the next
edition.

Simon
