### ISSUE TITLE
Minor corrections on chapter 18, version 31-01-23-C

### ISSUE THREAD

**Issue by danoneata** [udlbook/udlbook#23]
Thanks for releasing the book! I've enjoyed going through it!

Here are some typos that I could spot while reading chapter 18:

- page 361, line 1: missing a comma in the formula; should be $q(z_{1:t}, x)$
- page 361, second paragraph: $x$ has an extra subscript, should probably be $q(z_t|x)$ instead of $q(z_t | x_t)$
- equation 18.14: missing a left bracket
- equations 18.16 (last line) and 18.26: $σ^2_t$ should probably be $σ^2_1$
- equation 18.19: $Φ_{1...t}$ should probably be $Φ_{1...T}$
- section 18.4 onwards: $z_{1:t}$ should probably be $z_{1:T}$
- section 18.4 onwards: inconsistent indexing for $z$—previous material uses $z_{1:T}$, but here $z_{1‥.T}$ is used interchangeably
- section 18.4.1, last paragraph: by "modifying itself" should we also understand "optimize the parameters" (as it mentioned in the second item), or is there a subtle difference?
- section 18.4.2, first sentence: "minimize" should probably be "maximize"?
- algorithm 18.1: what is $q$? I assume it has nothing to do with the variational distribution, right?
- algorithm 18.1: I'm somewhat confused by the notation: $i$ and $\mathcal{B}$. I assume the former is the batched dataset? But then $i$ should range over batches?
- algorithm 18.2, last line: $g_1$ should probably be $f_1$
- section 18.6.1, last paragraph: shouldn't it say that $q(z_{t-1} | z_t)$ becomes closer to normally distributed with **larger** time steps?
- section 18.6.1, last paragraph (minor): I don't know if T should be encolsed in a math environment, i.e., $T$
- section 18.6.2, first sentence (minor): I don't know if you want to use the $t$ subscripts for the $α$'s (to match $z_t$)

The following questions might out of the scope of the book, but I do wonder:

- How are the fixed parameters (β, T, σ) chosen in practice?
- Can we (efficiently and accurately) estimate $p(x)$ for a given sample? This could be potentially useful for out-of-distribution detection. For example, I know that normalizing flows, while in principle could be used for estimating the model's probability, their performance usually suffers in practice [1]. For diffusion models, there is a discussion on this in section 2.3 of [2], but I'm not sure I follow their argument.

References:
- [1] Kirichenko, P., Izmailov, P., & Wilson, A. G. (2020). Why normalizing flows fail to detect out-of-distribution data. NeurIPS, 33, 20578-20589.
- [2] Sohl-Dickstein, J., Weiss, E., Maheswaranathan, N., & Ganguli, S. (2015, June). Deep unsupervised learning using nonequilibrium thermodynamics. In ICML (pp. 2256-2265). PMLR.

**Comment by udlbook** [comment]
Hi Dan,

Thank you so much for going above and beyond to point out these errors.  All fixed now and I've added your name to the acknowledgements.  I agree with all of them except that:

section 18.6.1, last paragraph: should say that becomes closer to normally distributed with a larger NUMBER of time-steps and smaller $\beta_{t}$.

In answer to your first question,  I know that people now use a cosine schedule for choosing the values of $\beta_t$.  See figure 3 of https://arxiv.org/pdf/2102.09672.pdf.    It's obviously key that (i) the $\beta$ values are large enough that the posterior distribution of z_{t-1} given z_{t} is close to normal and (ii) the original signal becomes pure noise at time T.  In fact, if you look at my example diffusion kernel, you can see that this is not the case -- I haven't used a large enough T and the result is that it doesn't generate enough samples for large x (in the histogram plots).  I'm going to remake these figures...

I think the terms $\sigma_t$ would be learned nowadays as part of the model.

I'm afraid that I don't really know the answer to your question about denoising.  The section you point out in the Sohl-Dickstein paper just says that the bound is pretty much tight with large enough beta_t terms.  So I guess it gives a sensible probability, but I have no idea if it would work in practice for identifying outliers.  Probably there are the usual problems with non-typical samples with a smaller norm being more likely (see figure 8.13).

Let me know if you find any more problems.  I'm sure there are still tons of them, particularly toward the end of the book.

**Comment by udlbook** [comment]
Arghh... I am struggling to make the accent under the "t" in your surname!  How do you do this in Latex?

**Comment by udlbook** [comment]
Oh... think I did it... Dan Onea\textcommabelow{t}\v{a}?

**Comment by danoneata** [comment]
Thank you very much for the additional explanations! They are very helpful, as always! (Although I think that in a couple of instances you might have meant "smaller" $\beta_t$ terms instead of "larger"?). Now I see that you have included a discussion on the sample probability in the VAE chapter (subsection 17.8.1); probably, the idea is very similar for the diffusion model case, although I see that Sohl-Dickstein et al. mention they need a _single_ sample for computing the probability.

Regarding my name, you can leave it without diacritics, if it's easier 🙂 Otherwise, in LaTeX it should be something like this:
```latex
\usepackage{combelow}
Dan Onea\cb{t}\u{a}
```

Thanks!

**Comment by udlbook** [comment]
Yes, sorry I meant smaller... forgot which way around it was.  Diacritics are in full effect and looking splendid.
