### ISSUE TITLE
20.1.2 Generalization

### ISSUE THREAD

**Issue by ronaldpan** [udlbook/udlbook#230]
1. there would be 10^40 possible inputs, which is a factor of 10^35 more than the number of training examples.
However, in 20.1.1, 10000 MNIST-1D training examples. 
10^35 should be 10^36.
2. A fully connected network for MNIST-1D with two hidden layers of width 400 can create mappings with up
to 1042 linear regions.
However, in 20.1.1, a two-layer fully connected network on 10000 MNIST-1D training examples is perfect once there are 43 hidden units per layer.
I was confused by these numbers.

**Comment by udlbook** [comment]
Hi

Apologies for the delay.   I've been on vacation and just returned today.

1. Yes, you are correct.  I have fixed this.  Thanks!
2. This is all referring to figure 8.10.  The network with the best test
performance in this figure has 400 hidden units per layer.  I have added a
reference to this figure to help resolve this confusion.

Simon
