### ISSUE TITLE
2 suspected errors

### ISSUE THREAD

**Issue by ILOVEDL2024** [udlbook/udlbook#232]
Hi Simon,

    In your great book UDL, I found two suspected errors at the beginnering and end of section 8.2 when you said "1D linear least squares regression problem" and "linear regression with a least squares loss". According to Figure 8.3 and 8.4, I think the model you mentioned is not "linear" and you may need to remove the word of "linear" there.

Your fan, Jo
Sep/07/2024

**Comment by udlbook** [comment]
Hi Jo,

Thanks so much for this and apologies for the delay in replying.  I've been
on vacation for the last two weeks.  I agree with your point and I'm
slightly embarrassed that this crept in.

I've fixed it and you'll see the changes when the online version is
next updated and when the book is reprinted (probably in about a year).

If you send your full name to the address on the front of the PDF, I'd be
honored to add it to the acknowledgements at the start of the book.

Simon
