### ISSUE TITLE
Potential Typo Regarding Reconstruction Loss in Section 17.4.2

### ISSUE THREAD

**Issue by Vanster78** [udlbook/udlbook#238]
Hi Simon,

In section 17.4.2. there's a statement:

> In this formulation, the first term measures the average agreement Pr(x|z, ϕ) of the latent variable and the data. This is termed the reconstruction loss.

I believe this might be slightly misleading, as reconstruction loss typically represents the opposite of agreement (high loss implies low agreement, and vice versa). So, it seems more accurate to say that this term represents the reconstruction term, while its negative is termed the reconstruction loss.

Does that interpretation make sense?

**Comment by udlbook** [comment]
Hi Ivan,

I agree.  I have made a small change.  I've also added your name to the
acknowledgements at the start of the book.  You'll see the change when I
next update the online version and when the book is reprinted again (some
time next year!).

Simon

**Comment by Vanster78** [comment]
Sounds great, thanks!
