### ISSUE TITLE
Typo in Fig 19.3 and doubt on Fig 19.4

### ISSUE THREAD

**Issue by linker81** [udlbook/udlbook#24]
Version 31_01_23_C
In the caption of Fig 19.3 is indicated "blue arrows" but in the figure the arrows don't look blue.

In the Fig 19.4 The policy a) doesn't lead the agent to the reward as indicated in the caption ("This policy generally steers the penguin from top-left to bottom-right where the reward lies"). The action in state 4 and 8 should be modified in "down".

Also the policy b) for different initial states don't reach the goal. Is it the desired behavior ?

**Comment by udlbook** [comment]
Hi -- I've tried to disambiguate these.  The policy in figure 19.4 isn't supposed to be optimal, but it's true that it mostly steers the penguin to the bottom right.

Actually, they will all reach the goal eventually because the penguin slips to a random position with some probability.
