### ISSUE TITLE
Formula 16.12 and 16.33, zero indexed phi?

### ISSUE THREAD

**Issue by aleksandrskoselevs** [udlbook/udlbook#246]
The latest vesrion of formula 16.12:

$$
f[h, \phi] = \left( \sum_{k=1}^{b-1} \phi_k \right) + (hK - b) \phi_b,
$$

with

$$
b = \lfloor Kh \rfloor + 1
$$

does not seem correct. For example:

$$
h = 0.1, K = 5, \phi_1=0.2 \\
$$

$$
b = \lfloor Kh \rfloor + 1 = \lfloor 5*0.1 \rfloor + 1 = \lfloor 0.5 \rfloor + 1 = 1
$$

$$
f[0.1, \phi] = \left( \sum_{k=1}^{1-1} \phi_k \right) + (0.1*5 - 1) * 0.2  = 0 - 0.8 * 0.2 = -1.6
$$

Since I'm using an older print edition, and did not notice the errata, I used the old definition of 

$$
b = \lfloor Kh \rfloor
$$

yet also noticed that there was something off in the formulation.

My fix was to assume that $\phi$ is zero indexed. This required adusting the start of summation:

$$
f[h, \phi] = \left( \sum_{k=0}^{b-1} \phi_k \right) + (hK - b) \phi_b,
$$

The previous example now looks like so:

$$
h = 0.1, K = 5, \phi_1=0.2 \\
$$

$$
b = \lfloor Kh \rfloor = \lfloor 5*0.1 \rfloor  = \lfloor 0.5 \rfloor  = 0
$$

$$
f[0.1, \phi] = \left( \sum_{k=0}^{0-1} \phi_k \right) + (0.1*5 - 0) * 0.2  = 0 + 0.5 * 0.2 = 0.1
$$

which aligns with what is shown in Figure 16.5.

If this formulation is correct, formula 16.33 of problem 16.9 would need the same adjustment.

Thank you.

**Comment by udlbook** [comment]
Hi - you are right.  I have actually fixed this (hopefully for the last time... it's my third try, at least) in a slightly different way, keeping the indexing starting with one.    You'll see then changes when I next update the online version and when the book is reprinted (next year some time)

Thanks so much for your help.  If you send your full name to the address on the front of the PDF, I'd be happy to add you to the list of acknowledgements at the start of the book!

**Comment by aleksandrskoselevs** [comment]
Dear Simon, 

I greatly appreciate you being so responsive here. My full name is Aleksandrs Koselevs, and I’ll make sure to send an email. I’d be honored to be included in the acknowledgments.

Looking forward to your solution! :)

Thanks,
Aleks
