### ISSUE TITLE
Other suggestions on chapter 19

### ISSUE THREAD

**Issue by linker81** [udlbook/udlbook#25]
Version 2023-02-02
Fig. 19.7: "Blue arrow" but the arrow is not blue
Eq. 19.7 --> I think that $\pi[a_t,s_t]$ should be substituted by $\pi[a_t|s_t]$
Eq. 19.11 --> I think it should be $\sum_{a_t}$ and not $\sum_{a}$
Eq, 19.12 -->I think it should be $\arg \max_{a_t}$ and not  $\arg \max_{a}$; $r[s_t, a_t]$ should substitute $r[s, a]$

**Comment by udlbook** [comment]
Thanks Amedeo.  I really appreciate your continued support.  A new version with a lot of bug fixes and the last chapter should be available later today.

**Comment by linker81** [comment]
Dear Simon, It is a pleasure and an honor to be able to contribute, even though in minimal part, to your great book.
