### ISSUE TITLE
Suggestions for Notebook 4.3

### ISSUE THREAD

**Issue by f-brinkmann** [udlbook/udlbook#250]
Thanks for creating all the notebooks - great way to put things into practive. A few minor suggestions for 4.3

- In the first markdown cell it should probably be 'This notebook investigates...' instead of 'This network investigates...'
- I found the matrix multiplications involving the beta_k and `np.ones` a little confusing at first and everything worked without them as well due to numpy's broadcasting. That would more closely follow the notation in the book.
- It might be nice to explicitly link to Eq. (4.15-4.16).

I tried to make a pull but the second I touch things in VScode, it generates a huge diff - so hope this is fine as well...

**Comment by udlbook** [comment]
Thanks so much Fabien!

These are all good points and I've made the changes.  No worries, it's
perfectly fine just to send me a TODO list if that works better for you.

Let me know if you find anything else.

S.
