### ISSUE TITLE
Answer booklet for students, Problem 16.11, Aproximating other density models, possible mistake

### ISSUE THREAD

**Issue by aleksandrskoselevs** [udlbook/udlbook#253]
The `Anwer Booklet Students` says:

$$
L = \sum_{i} \log \big[q(f[\mathbf{z}_i, \boldsymbol{\phi}])\big]
$$

However, solving it yields the following result:

$$
L = - \sum_{i} \log \big[q(f[\mathbf{z}_i, \boldsymbol{\phi}])\big]
$$

I can write this out if needed, however the formulation looks the same as the one the leads to equation `5.31`, so one would also expect a negative loss.

**Comment by udlbook** [comment]
Thanks so much!  Fixed.
