### ISSUE TITLE
Fig 5.1 and 5.11

### ISSUE THREAD

**Issue by jbr46** [udlbook/udlbook#26]
Just a couple of minor issues I think I've spotted:

Figure 5.1b): x axis of top right figure should run from 0 to 10 instead of 0 to 2, as in 5.1a) (or the probabilities below should read something like P(y | x = 0.4) and P(y | x = 1.4) )

Figure 5.1d): same as 5.1b)

Figure 5.11: the text in the grey rows is cut off at the bottom (makes [] look like the ceiling function ⌈⌉ )

Thanks for this great book, it's very helpful.

**Comment by udlbook** [comment]
Thank you so much.  I really appreciate it.  All fixed.  If you send your name to the address on the front of the pdf, then I'll add you to the acknowledgments.  Let me know if you find any more.
