### ISSUE TITLE
Suggestions on paragraph 19.5

### ISSUE THREAD

**Issue by linker81** [udlbook/udlbook#28]
Version 06-02-2023
Eq. 19.24: $\frac{\partial Pr(\tau_i | \theta)}{\partial \theta}$  -->  $\frac{\partial Pr(\tau| \theta)}{\partial \theta}$

Second line of Eq. 19.25: The same problem of equation 19.24

Check the second line of eq. 19.25: it looks like there is a not necessary ']' and the $\pi$ should be bold

Check the eq. 19.31: it looks like there is a not necessary ']'

**Comment by udlbook** [comment]
Thanks!  All fixed.  As you can tell, the stuff towards the end of the book hasn't been read so closely.  I hope that it wasn't too painful.
