### ISSUE TITLE
A few corrections and comments on chapter 17, version 06-02-23

### ISSUE THREAD

**Issue by danoneata** [udlbook/udlbook#29]
Hello! I've made a pass through chapter 17—thanks again for the very informative write-up! Here are some small corrections and some questions (you can of course ignore these more general comments if you think they are too distracting from the main point of the book):

- equation 17.2: $x$ should be bold, that is, $\mathbf{x}$
- equation 17.7, first line: missing a vertical bar to denote conditioning on the parameters, that is, $Pr(\mathbf{x}, \mathbf{z} | \mathbf{Φ})$
- figure 17.6, caption: "by either a) improving the ELBO" should be "by improving the ELBO either a) with respect to ... or b) with respect to ..."
- figure 17.6: the caption says that "we get closer to the true log likelihood by improving the ELBO [...] with respect to the original parameters φ", but the figure on the right indicates that the gap increases. I would assume that the statement is correct (since, for example, diffusion models close the gap even if they use a fixed variational distribution), but that means that the figure is somewhat deceiving?!
- figure 17.12: contains a self reference (that is, the caption mentions "figure17.12", which is incidentally also missing a space).
- subsection 17.8.3 mentions "the product $Pr(\mathbf{z}|\mathbf{x})Pr(\mathbf{z})$": I was wondering is there a principled justification of multiplying the prior $P(\mathbf{z})$ with the posterior $P(\mathbf{z}|\mathbf{x})$? It seems a bit unnatural to me from a probabilistic point of view, but maybe this is just motivated from a more pragmatic perspective?!
- subsection 17.8.4, equation (17.29):
    - the variable $\mathbf{z}$ seems to be unbound—where does it come from?
    - are there any properties particular properties that the functions $r_1$ and $r_2$ should have? Defining the regularization terms as arbitrary functions seemed a bit too general to me (e.g., they can negate their input argument or completely ignore it).
    - any intuition on why these two regularization terms encourage disentanglement? Are they related to beta-VAE and total correlation VAE? (It was not immediately clear to me the connection between those concepts.)
    - (minor) if $L_\mathrm{new}$ denotes a loss, maybe it would be a bit more precise to use a negative ELBO and positive regularizes?
- page 352: Maybe the wording can be improved in the following: "[...] then autoencoder is just [...] PCA. Hence, the autoencoder is a generalization of PCA."; for example, by saying "Hence, a _nonlinear_ autoencoder is a generalization of PCA," or something along these lines?
- page 352, second paragraph on "Latent space, prior and posterior": there is an undefined reference
- page 353, paragraph on "Posterior collapse", last sentence: there is an undefined reference
- page 353, paragraph on "Other problems":
    - From the description the "information preference" problem seems very similar to posterior collapse. What is the difference between the two?
    - The paragraph cites Chen et al (2017) for InfoVAE, but I wonder whether the correct reference isn't
> Zhao, Shengjia, Jiaming Song, and Stefano Ermon. "InfoVAE: Information maximizing variational autoencoders." AAAI (2017).
- page 354, paragraph on "Disentangling latent representation": "e.g.," should probably be "etc."?
- equation 17.35:
    - is the subscript $z$ correct in the expectation? There is no $z$ defined elsewhere.
    - on the left hand side of the equation "f" is written in roman typeface, while on the right it is written in italics; is this correct? I'm yet sure what is the convention for each of the two variants.

**Comment by udlbook** [comment]
Thanks so much.  As you can see, the later chapters are not so well proofed, so this was incredibly useful.  Hope it wasn't too painful.

Good spot with the InfoVAE citation!

My understanding is that posterior collapse is a problem with the encoder (it always predicts the same posterior distribution over the hidden variables) and information preference is a problem with the decoder (it ignores the hidden variables and model the data as a constant mean plus noise).

The statement in figure 17.6 was wrong.  I'm just trying to say that the log likelihood increases (or gets closer to the maximum log likelihood solution).  The product Pr(z|x)Pr(z) was a mistake.  Should have been Pr(x|z)Pr(z).

Thanks again for this detailed read.  Super-helpful!

**Comment by danoneata** [comment]
> My understanding is that posterior collapse is a problem with the encoder (it always predicts the same posterior distribution over the hidden variables) and information preference is a problem with the decoder (it ignores the hidden variables and model the data as a constant mean plus noise).

Thanks for the clarification! But I still wonder whether the two cases are not just equivalent: p(z|x) = p(z) (posterior collapse) is equivalent to x ⫫ z (independence between latent and observed variables), which in turn is equivalent to p(x|z) not depending on z (information preference).

>  I'm just trying to say that the log likelihood increases (or gets closer to the maximum log likelihood solution). 

I see, but don't we need some additional assumptions for that to be true either: _e.g._, the E step should yield a tight bound, or the increase in the M step should be larger than the gap?

**Comment by udlbook** [comment]
They aren't equivalent if you consider the data that is generated.   In posterior collapse, it will be able to generate complex structured data as it samples from the hidden variable and passes this through the decoder.  It will probably generate the wrong data, since we need the encoder to work for training and it is broken, but it will generate a variety of different outputs.

In information preference, the generated data doesn't depend on the hidden variables.  So it just depends on the biases in the decoder plus the final additive noise.  Since, we don't usually show this noise, every sample would look the same.

On the other topic, I don't think that we need additional assumptions once I am no longer claiming that the bound is getting closer to the true log likelihood.  We are just improving the bound at each step and we know we are doing this because we are using an optimization algorithm that will (hopefully) terminate when the improvement ceases.
