### ISSUE TITLE
page 100 and page 103

### ISSUE THREAD

**Issue by karaikyo** [udlbook/udlbook#30]
Book version 06_02_23_C

On page 100, below equation 7.6, "We aim to compute the derivatives: .... and $\partial y/\partial \omega_4$." Is  $\partial y/\partial \omega_4$ a typo?

On page 103, caption of Fig 7.5, should be "... the derivatives $\partial l_i / \partial \beta$ and $\partial l_i/ \partial \omega$", and "... by $\partial l_i/ \partial \beta_k$ or $\partial l_i/ \partial \omega_k$ as appropriate."

P.S.
For the PDF version, is it possible for you to add chapter numbers to the navigation panel? There are places in the book where you say something will be discussed in Chapter XX, and I think it'll be much easier to locate the chapters for PDF readers.

Thank you very much for your great work.

**Comment by karaikyo** [comment]
page 114, paragraph "Reducing memory requirements", line 6, there's an extra letter 'f' in the 1st word 'forward'

**Comment by karaikyo** [comment]
page 114, paragraph "Reducing memory requirements", line 6, there's an extra letter 'f' in the 1st word 'forward'

**Comment by udlbook** [comment]
Thanks, Lei He.

I've made these changes and added your name to the acknowledgements.

 I actually added this 1D backprop section only a few weeks ago, so it's
not surprising it has some mistakes in it.

I'd be happy to add the chapter numbers to the pdf, but I have no clue how
to do that.  Do you know?  For what it's worth, the chapter references are
links.  If you click on the number, it will move you to the chapter in
question.

Let me know if you find any more issues.  It's super-hard to proof your own
work on this scale.

Simon
