### ISSUE TITLE
Page 112 code indentation

### ISSUE THREAD

**Issue by siqi-zheng** [udlbook/udlbook#33]
There is a small indentation issue on the latest version. The `for i, data in enumerate(data_loader):` statement should has the same indentation as `epoch_loss = 0.0`
![Screenshot](https://user-images.githubusercontent.com/64695253/220739458-26948c95-48d0-484f-b5cb-014236a89153.jpg)

**Comment by udlbook** [comment]
Thanks Siqi,

I've fixed that and added your name to the acknowledgements.  I appreciate your help!  Please let me know if you find any more problems.  It's super-hard to find typos in your own work.

Simon
