### ISSUE TITLE
typo in page 147, section 9.3.3

### ISSUE THREAD

**Issue by kono-dada** [udlbook/udlbook#36]
In the second paragraph of section 9.3.3 "Dropout", a word "kinks" occurs. I guess it might be "links".

**Comment by udlbook** [comment]
Hey -- this is not actually a typo. It's meant to say kinks and it refers to the phenomenon in figure 9.9a.  I agree though that the word is a little surprising, so I've put it in inverted commas now.   Hopefully, this will make it easier to read.

**Comment by kono-dada** [comment]
Sorry, actually I am not a native English speaker, and I did not find the word "kink" in my e-dictionary. This is a misunderstanding and I feel sorry for it.

发自我的 iPhone

在 2023年2月26日，01:32，udlbook ***@***.***> 写道：

﻿

Hey -- this is not actually a typo. It's meant to say kinks and it refers to the phenomenon in figure 9.9a. I agree though that the word is a little surprising, so I've put it in inverted commas now. Hopefully, this will make it easier to read.

**Comment by udlbook** [comment]
No need to feel sorry.  I really appreciate that you are willing to help
me.   There are definitely some mistakes in the book still, so let me know
if you find any more things that you think are wrong.

Simon
