### ISSUE TITLE
partial derivatives is inconsistent in the equations

### ISSUE THREAD

**Issue by jsantarc** [udlbook/udlbook#39]
The order of partial derivatives is inconsistent in the equations. While the partial derivatives themselves are correct, they are arranged in different orders. In equations 7.11 and 7.12, when we apply the chain rule, the first term for the loss with respect to the pre-activation starts on the left, and each subsequent term goes on the right, i.e., the terms are ordered from left to right. However, in equations 7.17-7.19, the order is from right to left. 

EQ 7.12
<img width="463" alt="Screenshot 2023-02-27 at 5 18 11 PM" src="https://user-images.githubusercontent.com/10367519/221699332-4e677c74-a221-495c-a628-ecd7bef69804.png">

EQ  7.18 and 7.19
<img width="499" alt="Screenshot 2023-02-27 at 5 18 33 PM" src="https://user-images.githubusercontent.com/10367519/221699492-7b403c81-2d5f-4e87-a24d-0b344637d686.png">

This maybe due to order of matrix multiplication

**Comment by udlbook** [comment]
Ah... well spotted.  Wrote these two parts six months apart.  I have fixed it and added your name to the acknowledgements.  Let me know if you find any more.  It's extremely difficult to find this kind of error in your own work.

Simon
