### ISSUE TITLE
Page 434 Figure B.3

### ISSUE THREAD

**Issue by YifeiLin0226** [udlbook/udlbook#41]
The figure text '...is used to show that the Kullback-Leibler divergence is always greater than one'. The KL divergence should be always greater than zero.

**Comment by udlbook** [comment]
Thanks!  The Appendices are still a bit of a mess, I'm afraid.  Fixed now.  If you send me your name to the e-mail address on the front of the pdf, I'll add you to the acknowledgements.  Can't be 100% sure from your GitHub username...
