### ISSUE TITLE
Notation erratum, page 49 (v. 2023-03-03)

### ISSUE THREAD

**Issue by zkrlotfi** [udlbook/udlbook#45]
In v. 2023-03-03:
Page 49, Sec. 4.4.1:

"the remaining matrices $\Omega_k$ are $D_k \times D_{k-1}$"

I think that following the same notation as the first part of this section it should be:
" $\Omega_k$ are $D_{k+1} \times D_{k}$"
Or
" $\Omega_{k-1}$ are $D_k \times D_{k-1}$"

**Comment by udlbook** [comment]
Oooh.  Good catch!  Thank you so much for all of your comments.  Please let me know if you find any more.  If you send your full name to the e-mail address on the front of the pdf, I'll add you to the acknowledgments.
