### ISSUE TITLE
Minor notation errata, pp. 421-422 (v. 2023-03-03)

### ISSUE THREAD

**Issue by zkrlotfi** [udlbook/udlbook#47]
In v. 2023-03-03
Page 421, Appendix A, Sets:

- "The notation $\\{\boldsymbol{\mathrm{x}}_i, \boldsymbol{\mathrm{y}}_i\\} _{i=1}^I$ denotes the set of $I$ pairs $x_i, y_i$ ."
Since x and y are vectors and not scalars I think it should be:
"The notation $\\{\boldsymbol{\mathrm{x}}_i, \boldsymbol{\mathrm{y}}_i\\}^I _{i=1}$ denotes the set of $I$ pairs $\boldsymbol{\mathrm{x}}_i, \boldsymbol{\mathrm{y}}_i$."

- In $\\{1, 2, 3, ...,\\}$ I would remove the last comma: $\\{1, 2, 3, ...\\}$

Page 422, Appendix A, Sets:
- In $\\{1, ... K\\}$ I would add a comma just before $K$: $\\{1, ..., K\\}$

**Comment by udlbook** [comment]
Thanks again.  All fixed.
