### ISSUE TITLE
Minor errata, pp. 56-60 & 426(v. 2023-03-03)

### ISSUE THREAD

**Issue by zkrlotfi** [udlbook/udlbook#48]
In v. 2023-03-03
Page 56, Loss functions:

- For binary classification, I think " $y \in [0, 1]$ " should be " $y \in \\{0, 1\\}$ " because it's a set of two integers (or classes) not an interval of all possible real values between 0 and 1.
- For multiclass classification, I think " $y \in [1, 2, ..., K]$ " should be " $y \in \\{1, 2, ..., K\\}$ " for the same reason

Page 57, figure 5.1 :

- " $y \in \mathcal{R}$ " should be " $y \in \mathbb{R}$ "

Page 58, Sec. 5.1.1 :
I'm probably wrong about these, but :
- "on the output domain $\boldsymbol{\mathrm{y}}$ ", "the prediction domain is $y \in \mathbb{R}$ " and " which is defined on $y \in \mathbb{R}$ " seem a little odd to me, because the definition domain is $\mathbb{R}$ (or $\mathbb{R}^D$ in the first one) not $y$ (or $\boldsymbol{\mathrm{y}}$). The only case where I would put $y$ is if I wrote it as a set $\\{y \in \mathbb{R}\\}$.
- "The machine learning model $\boldsymbol{\mathrm{f}}[\boldsymbol{\mathrm{x}}, \boldsymbol{\phi}]$ ", are you always talking about a univariate problem ? If it's the case then it should be " $\mathrm{f}[\boldsymbol{\mathrm{x}}, \boldsymbol{\phi}]$ ".
- In the footnote "As a function of $\phi$ " should be "As a function of $\psi$ "

Page 60, equation 5.5 :

- I believe $\phi$ needs a hat $\hat{\phi}$ because it was estimated by minimizing the negative log likelihood (like in equation 5.12).

Page 62, equation 5.12 :

- I believe $\mathrm{f}$ shouldn't be bold because it returns a scalar: $\mu$ or as explained later $\hat{y}$

Page 426, B.1.5 :

- "If the value of the random variable ~~**variable**~~ $y$ "

**Comment by udlbook** [comment]
Thanks so much!  You have amazing attention to detail.  I've probably read this twenty five times and missed all of those.  Makes me scared about what else is in there...

I've added your name to the acknowledgments at the start of the book.  Let me know if you find any more.  It's super hard to proof your own work on this scale...
