### ISSUE TITLE
Section 5.6 regression vs classification

### ISSUE THREAD

**Issue by sbouix** [udlbook/udlbook#52]
> "For example, we might want to predict a molecules melting and boiling point (a multivariate **classification** problem, figure 1.2b) or the object class at every point in an image (a multivariate classification problem, figure 1.4a)"

The molecule melting and boiling point is a regression model I think. Should this be replaced by "(a multivariate **regression** problem, figure 1.2b)"?

**Comment by udlbook** [comment]
Oooh.  Good catch.  Regression, of course.  Thank you so much.  I've added your name to the acknowledgements.  Please let me know if you find any more.  I'm really struggling to proof this on my own.
