### ISSUE TITLE
Minor typo in Eq. 17.26

### ISSUE THREAD

**Issue by roobnloo** [udlbook/udlbook#54]
The term $d\mathbf{z}$ should appear after the integrand in the first line and not after the expectation.

![image](https://user-images.githubusercontent.com/71776622/224849015-0c61fa97-a3a8-4087-951b-0a8da325a5c8.png)

**Comment by udlbook** [comment]
Good spot Robin!  Thanks.  Let me know if you find any more.  The last few chapters probably have quite a few in them.  I've added your name to the list of acknowledgements.
