### ISSUE TITLE
Minor typos

### ISSUE THREAD

**Issue by computbiolgeek** [udlbook/udlbook#55]
Dr. Prince, there seem to be some typos in the March 11 version:

- On page 92, line 3 of the **Properties of SGD** paragraph: "there there" -> there? 
- In the caption of Figure 11.4 on page 191, did you mean "The **input** of each function ... is added ~~back~~ to its **output**" rather than "output added back to input"? I suppose both ways are fine, but "input added to output" seems a bit clearer. Similarly in line 3 of the caption of Figure 11.6.
- Page 419, line 3 of the summary section: "most two important" -> "two most important"?

Again, thank you very much for this fantastic work!

**Comment by udlbook** [comment]
Thanks so much and glad that you are enjoying it.!  I fixed all of these and added your name to the acknowledgements.  Please let me know if you find any more.
