### ISSUE TITLE
Typos in Chapter 17

### ISSUE THREAD

**Issue by computbiolgeek** [udlbook/udlbook#56]
Dr. Prince, there seem to be a few typos in Chapter 17:

- Page 330, in the caption of Figure 17.4, $\log[E[y]] > E[\log[y]$ is missing a closing square bracket
- Page 332, in the caption of Figure 17.6, "we can ~~get~~ increase" -> we can increase?
- Page 339, in the second line of equation 17.26, remove $d\mathbf{z}$, i.e. $E_{\mathbf{z}}[Pr(\mathbf{x|z})]d\mathbf{z}$ -> $E_{\mathbf{z}}[Pr(\mathbf{x|z})]$?

A suggestion, would it be better if $Pr(\mathbf{z})$ in equation 17.22 is replaced with $q(\mathbf{z}|\mathbf{x},\mathbf{\theta})$ because the sample is taken from distribution $q(\mathbf{z}|\mathbf{x},\mathbf{\theta})$? 

Your work has really helped me understand what's under the hood. Thank you very much for making it freely accessible.

**Comment by udlbook** [comment]
Thank you so much again!  I agree with all of these points and have made the corrections.  Let me know if you find any more!
