### ISSUE TITLE
Unclear sentence in section 17.2

### ISSUE THREAD

**Issue by AndreaPi** [udlbook/udlbook#60]
Version 04/06/2023

> The latent variable z is smaller than the data x.

**z** and **x** are random variables, so what do you mean by "**z** is smaller than **x**"? I don't think you're referring to [stochastic ordering](https://en.wikipedia.org/wiki/Stochastic_ordering). Maybe consider rewording this sentence?

**Comment by udlbook** [comment]
Thanks! -- I just mean that z is is lower dimensional than x.  I've fixed this now and added your name to the acknowledgements.

Let me know if you find any more!
