### ISSUE TITLE
Missing policy symbol? 19.2.1

### ISSUE THREAD

**Issue by AndreaPi** [udlbook/udlbook#61]
Version 05/06/2023

> We can characterize how “good” a state is by considering the expected return v[s_t].

The value state function depends also on the policy, so maybe it would be better to denote it as v[s_t|\pi], as done in eq. 19.2 immediately afterwards.

**Comment by AndreaPi** [comment]
I see that the notation v[s_t] and v[s_t|\pi] are used interchangeably across the chapter, so it probably doesn't make sense to change it here. Closing the issue

**Comment by udlbook** [comment]
I think this was actually a good point.  I tried putting in all the |\pi terms, but honestly it makes a mess.  So now I'm consistent up to a point, where I explicitly say that we are dropping this from the notation.  Thanks!
