### ISSUE TITLE
Error in Figure 19.8

### ISSUE THREAD

**Issue by AndreaPi** [udlbook/udlbook#62]
Figure 19.8: the values of state for state 2 and state 5 are inverted:

![image](https://user-images.githubusercontent.com/8233615/230741752-08ef0cac-975b-4ef1-beee-148ad46114ab.png)

The same error is present in Figure 19.9. Also, both figures seem to illustrate how the value of action depends on reward and the subsequent states, but figure 19.8, according to the description, should show how the value of state depends on the policy and the values of action:

> Figure 19.8 Relationship between values of state and action. The value of state
six v[st = 6] is a weighted sum of the values of action q[at, st = 6] at state six,
where the weights are the policy probabilities π[at|st=6] of taking that action.
Figure 19.9 Relationship between values of action and state. The value q[at =
2, st = 6] of taking action two in state six is the reward r[at = 2, st = 6]
from taking that action plus a weighted sum of the discounted values v[st+1]
of being in successor states, where the weights are the transition probabilities
Pr(st+1|st = 6, at = 2). The Bellman equations chain this relation with
the relation

Maybe figure 19.8 should be something else?

**Comment by udlbook** [comment]
Thanks Andrea!

What a mess!  Yes you are right, fig 19.8 should be something else.  I've fixed that now and will post a new version later today.  Apologies for the confusion.  I've also fixed the mistake in this figure that you identified.

Let me know if you find any more.
