### ISSUE TITLE
Small error on Page 210 (v. 2023-04-08)

### ISSUE THREAD

**Issue by rohan-ajwani** [udlbook/udlbook#63]
Dear Dr. Prince,

On page 210, the line below eq. 12.4 says "where q_n and k_k are referred ....". I believe it should be "where q_n and *k_n ..." (ie. subscript for k should be n instead of k)

Thanks!

**Comment by udlbook** [comment]
Thanks so much, Rohan!  It's fixed now and I've added your name to the acknowledgments.  Let me know if you find any more.  It's super-hard to proof your own work, and I'm desperate for help!
