### ISSUE TITLE
used different encoder parameter for VAR in chapter 17 vs chapter 18 

### ISSUE THREAD

**Issue by jsantarc** [udlbook/udlbook#64]
Chapter 18 on page Page 357 

> In the VAE, the encoder q(φ) approximates the posterior distribution over the latent variables to make the bound tight, and the decoder maximizes this bound (figure 17.10). In diffusion models, the decoder must do all the work...

but you  define the encoder  as function z given x  and the parameter of  θ not φ in chapter 17 as shown here 
q(z|x, θ)

**Comment by udlbook** [comment]
Hey Joseph, sorry for the slow reply.  Honestly, it took me a while to figure out what you meant, but I was just being stupid.  Of course, you are correct.  I have fixed this now and added your name to the acknowledgements.

Thank you very much!  Let me know if you find any more.
