### ISSUE TITLE
Minor Typos? in Section 5.6

### ISSUE THREAD

**Issue by shashashak** [udlbook/udlbook#65]
I think I found some minor typos in **Section 5.6 Multiple outputs**, specifically **page 69**.

**original**

> To predict multiple discrete variables **$y_d \in [1, 2, ..., K]$**, .....  each $y_d$. Here, each set of networ outputs **$f_d[x_i, \phi]$) predicts** ....

first, $y_d \in [1, 2, ..., K]$ $\Rightarrow$ $y_d \in$ { 1, 2, ..., K }, because $y_d$ follows a categorical distribution 
second, it needs to be deleted ")" in $f_d[x_i, \phi]$)

I'm not 100% sure. please, would you check those sentences?

**Comment by udlbook** [comment]
Thanks so much!  You have a great eye for detail.  I've fixed these.  If you send me your real name to the address on the front of the document, I'd be happy to add you to the acknowledgements.

Let me know if you find any more problems.

Simon
