### ISSUE TITLE
Where are the notebooks referenced in the book?

### ISSUE THREAD

**Issue by fabiogomez11c** [udlbook/udlbook#68]
Hi!

Great book, pretty much what I wanted. I've been reading it but sometimes I see some references to notebooks, e.g: `Notebook 7.2 Backpropagation`, but I don't find that notebook anywhere.

Thanks!

**Comment by udlbook** [comment]
Hey -- there are prototypes in my github:

 https://github.com/udlbook/udlbook

All the files that end in .ipynb.  However, they aren't numbered as in the book yet and they only go to chapter 12.  

I'll be working on these during the next six months or so.
