### ISSUE TITLE
Ch 16 Normalizing Flows Figure 16.1 plots (a) and (c)

### ISSUE THREAD

**Issue by pieris98** [udlbook/udlbook#69]
Hello Prof. Prince. Thank you so much for the book, it's really the most intuitive and visual book I've seen on the planet for (deep) deep deep learning :1st_place_medal:  Wish you all the best with the publication and definitely going to get myself a physical copy in the future!
I'm studying Normalizing Flows at the moment (latest 26th April draft of the book). I noticed that on page  305 the y-axis for Figure 16.1 (a) (Base Density) and (c) (Model Density) are missing. I'm not sure if you omitted those intentionally, however I think it would be less confusing to move Pr(z) and Pr(x) to the y-axis as labels, while the x-axis would be labelled as just z and x respectively. 
I've drawn a sketch of the changes below,
Thank you again for your service!
![Screenshot from 2023-05-01 04-05-26](https://user-images.githubusercontent.com/34139689/235371779-3836c012-9e16-4b9f-819a-0294beefa0c9.png)

**Comment by udlbook** [comment]
Well spotted!  I can't believe I have seen that figure so many times and not noticed it.  Fixed now and I've added your name to the acknowledgements.  Thank you very much!  Let me know if you find anything else.
