### ISSUE TITLE
19.2.3 and following: order of arguments in the reward function

### ISSUE THREAD

**Issue by AndreaPi** [udlbook/udlbook#70]
This is not really an error, but a minor inconsistency in notation, so it's up to you if you want to change it or not. In the whole chapter, for _nearly_ all the function that depend on both $s_t$ and $a_t$, $s_t$ comes first in the arguments list: 
 
- Transition probabilities: $Pr(s_{t+1}|s_t, a_t)$
- State-action value function: $q(s_t, a_t)$
- The deterministic rewards too, the first time they appear (paragraph 19.1): $r[s_t, a_t]$

However, from paragraph 19.2.3 onwards, the order of arguments is switched and reward is always written as $r[a_t, s_t]$. This is especially evident when you have a lot of $q(s_x, a_x)$ in the same expression, as in the case of SARSA and Q-learning (respectively eq. 19.14 and 19.15). It's not a big deal, of course. However,  since the order of arguments stay the same in all the other functions of $s_t, a_t$, you may want to consider whether it's the case to enforce consistency or not.

**Comment by udlbook** [comment]
Good point.  I've fixed this.
