### ISSUE TITLE
Error about stochastic reward in paragraph 19.4.2

### ISSUE THREAD

**Issue by AndreaPi** [udlbook/udlbook#73]
> The stochastic reward will exceed the average half of the time and be chosen by the maximum operation, causing the corresponding value of action $q[s_t, a_t]$ to be overestimated.

While you clearly convey the main idea, a random variable (reward) is not higher that its mean (or average) half of the time. This is true for the median, but not for the mean. For some distributions (e.g., exponential distribution, chi-squared distribution, etc.) the mean is actually larger than the median, thus the random variable won't be higher than the mean half of the time, but less often.

**Comment by udlbook** [comment]
Oooh... subtle, but good point. I will reword.
