### ISSUE TITLE
Minor issues

### ISSUE THREAD

**Issue by alexwpitt** [udlbook/udlbook#75]
Hi there,

Thanks again for your book. I hope these are of some use.

PDF release UnderstandingDeepLearning_03_05_23_C.pdf

PDF page 230, Figure 12.7
Missing reference to figure in text?

PDF page 283, Figure 14.1
Missing reference to figure in text?

PDF page 302, Section 15.4.2
Terminology consistency? "by requiring that the ~~classifier~~ _discriminator_ correctly predicts the attribute" 

PDF page 309, Section 15.5.3
Word omission? "The cycle-consistency [loss] will be low if the translated image..."

PDF page 394, Figure 19.9
Notation consistency? "The value ~~q[a_t=2, s_t=6]~~ _q[s_t=6, a_t=2]_ of taking action two..."

PDF page 427, Figure 20.12
Missing reference to figure in text?

Cheers,
Alex

**Comment by udlbook** [comment]
Thank you so much, Alex.    You have a good eye for detail.  Let me know if you find any more.
