### ISSUE TITLE
Missing hyphens? etc

### ISSUE THREAD

**Issue by sfikas** [udlbook/udlbook#8]
In pages 27 and 59 (v. 7-10-22-C-5) the word "multidimensional" is written without a hyphen, right before eq. 3.11.
Also, in page 90, you write "one dimensional", where in most places this is 1D.

These are very minor of course, I'm just letting you know in case you want to normalize w.r.t. the norm throughout the text.

**Comment by sfikas** [comment]
And one more regarding normalization throughout the text: "LeCun" is written "Lecun" at page 105.

**Comment by sfikas** [comment]
The "Table of contents" at https://udlbook.github.io/udlbook/ is currently missing chapter 10, "Convolutional networks". Also, it appears at the "Resources for instructors" section but as "Convolutional nets".

**Comment by udlbook** [comment]
Thanks so much, Giorgos. Yes -- I definitely care about all of these small things, and I've fixed them all.  You'll see the changes in a few weeks time when I release the next version.  I've added your name to the acknowledgements.

Please let me know if you find anything else.

**Comment by sfikas** [comment]
You're welcome, and thanks for such a great new book!
