### ISSUE TITLE
Questions on Normalizing Flows

### ISSUE THREAD

**Issue by limesqueezy** [udlbook/udlbook#80]
Professor Prince,

I first want congratulate you for putting such an immaculate book out for everyone. I had a bit of trouble in understanding the following two graphs. Maybe because of my own goofiness or a typo in the book.

---

On the normalizing flows chapter, page 310 of the `08_05_23_C` release we have,

$K$ representing the number of regions, in this case 5. 

$h$ representing the input domain (constrained in [0-1]).

$b$ representing the bin of $h$.

My question is on how we get $\sum\limits_{i=1}^{K}{\phi_i}=1$ in figure `16.5 b`? From what I understand figure `b` essentially shows that $\frac{dh^\prime}{dh}=\phi_b$ (where `b` is the bin index that contains `h`) which is not true since $\frac{dh^\prime}{dh}=\mathbf{K}\phi_b$, at least according to equation `16.12`.

> Each region has a slope with parameter, $\phi_k$ . a) If these parameters are positive and sum to one

I think what this statement argues is that gradients $\phi_k$ sum to 1 which pictorially is not the case.

A follow-up question to this are the two extrema of equation `16.12`,

* Since $h\in (0.0,0.2]$ let's pick $h=0.2$ (or else $b=0$ and we would have an even bigger issue), $b=1$, $f(h_d;\phi)= \sum\limits_{k=1}^{0?}...$
* For $h=0.9$, $b=4$, $f(h_d;\phi)= \phi_1+\phi_2+\phi_3+0.5\cdot\phi_4$ (should be $\phi_5$ since we're in the last bin)
* For $h=1$, $b=5$, $f(h_d;\phi)= \phi_1+\phi_2+\phi_3+\phi_4$

Assuming this was an OB1 in the limits of the summation $f(h_d;\phi)= \sum\limits_{k=1}^{b}\phi_k+(Kh-b)\phi_b$,

* For $h=0$, $b=0$, we still get an OB1 therefore I suggest we also put this extra constraint $h\in (0,1]$ 
* For $h=0.1$, $b$ is still $0$ but assuming that the reason for the first summation being invalid is that we should consider it as `0` the rest works out **almost** fine, $f(h_d;\phi) = 0.5\cdot\phi_0$. There's no $\phi_0$.

I think we need to change the equation since $b$ represents two things,

1. A base for the relative proportion of the way through the current bin i.e. what $b$ is right now
2. The actual bin index which is $b+1$ 

Overall we would get the following under the major assumption of having invalid summations,

1. $h\in (b,b+1]$
2. $f(h_d;\phi)= \sum\limits_{k=1}^{b}\phi_k+(Kh-b)\phi_{b+1}$ 

---

In figure `16.9 b` I cannot make out what the y-axis would represents exactly. If `f(z)` is the same function as in figure `16.9 a` then I get even more confused since `f(z)` must be negative to get values larger than $y^\*$ for inputs less than $z^\*$.

---

Aside those two questions I have seen throughout this book a couple of linked Jupyter notebooks that would be extremely useful for my understanding but I could not find them anywhere :(

Thank you again, I hope you can get it finalized soon so we can all have a physical copy and your efforts are paid off!

Kindest regards,
Ari

**Comment by udlbook** [comment]
Hi Ari, 

Thanks for these comments.  It took me *LONG* time to figure this out, but I think you are right, equation 16.12 has a mistake in it.  The second term should be divided by K.  The gradients should also sum to K.   I think this makes everything correct, although I was struggling to understand the latter part of your argument, so please clarify you don't think this sorts things out.   


The y axis in equation represents two different things (according to the two colored lines).  I agree, potentially confusing, but I couldn't figure out how to improve it.

Thank you so much for your help.

I don't know your surname (unless you are the other Ari who is e-mailing me), but if you send it to me, I will add you to the acknowledgements.

I haven't really started working on the notebooks yet -- the book doesn't actually come out until December.  There are some rough versions for chapters 1-12 if you root around my GitHub though.
