### ISSUE TITLE
Chapter 3, Universal approximation theorem, clarification

### ISSUE THREAD

**Issue by Nikolaj-K** [udlbook/udlbook#81]
It could be that page 38 (Universal approximation theorem:) cheats with the quantifiers, which makes it misleading if not just wrong: 
It's not the case 
"that a network... containing a finite number of hidden units ... can approximate any continuous function ... to arbitrary accuracy."
Instead, for any given function and given precision, there exists an approximating network. Not the other way around. 
If one really wants to name the networks first, then one could say 'using the class of networks (or this and that form), one can approximate any function to any precision'

I might be wrong but I'd check those. 
I say _those_ because some version of the theorem is brought up between 29 and 53. I'm not sure if it's possible to bring the two "Notes" called "Universal approximation theorem" together, but both of them are not super sharp on what then theorem says in the above sense. 

In the end of page 29 you end with "and this is known as the universal approximation theorem." - do you mean the one for ReLu's here? Since we've seen the 1D ReLu example and the piecewise-linear construction, this seems like it's understating "the" theorem (I suppose the standard forms either apply to lots of activation functions or really narrow width).

**Comment by Nikolaj-K** [comment]
It looks like this PhD thesis has a nice more or less recent survey

http://www.matfis.uniroma3.it/Allegati/Dottorato/TESI/costarel/Sigmoidal_Approximation_Costarelli.pdf

**Comment by udlbook** [comment]
Hi Nikolaj, 

Thank you so much for engaging with this.

I have a chance to make some final changes tomorrow.  However, I'm embarrassed to say that I think that this topic is honestly beyond my technical ability to do it justice (at least in the time that I have).  I don't think that I can bring those parts together because of issues with typesetting, but I could change the wording of each if you have specific suggestions.  It needs to take a similar amount of space though.

Overall, the statement on page 29 is just supposed to say that the universal approximation theorem is a thing and then the actual citations are on page 38.  Happy to receive concrete suggestions about either.

Simon

**Comment by Nikolaj-K** [comment]
Let me elaborate more explicitly:

Firstly, here's one formulation from Wikipedia:

<img width="982" alt="Bildschirmfoto 2023-05-31 um 22 08 07" src="https://github.com/udlbook/udlbook/assets/27020510/4ed3351e-330a-4a66-b656-ba769b48cc47">

This concerns 1-layer networks of width k.
For simplicity, let's consider n=m=1, i.e. you have 1 real input and 1 real output.
Let's also, for \sigma, we take the classical sigmoid (1/(1+exp(-x))) and in particular, we're in the situation where \sigma is not a polynomial.

The theorem then exactly says: 
* For any f into R (and floating point values in praxis), meaning for any graph/line you might plot (say we pick some sinodial graph or whatever)
* and for any precision eps (say we pick 10^-14 as accuracy we're fine with)
* there exists a k (meaning numbers of vertices in our network "net" with its 1 layer)
* such that for any input x, the true values f(x) and net(x) are everywhere at most eps apart.

If you read again the Wikipedia quote, this is fairly straight forwardly what it says.

Say in praxis you choose your domain and your f and your eps. And you test it and you find 
"wew, okay I need k=545234" nodes in my network, but indeed it looks like my `net` with my fat 1 layer of size 545234 always returns the same value as f."
Say you find some value where f(x) (Mathematica) vs. your net(x) is 10^-15 apart and this is your worst closeness you find.
Okay, but now say your boss actually say "no Simon, this isn't good enough, I want the computed value to lie eps 10^-17 and not just 10^-14"
To achieve this, you will have to raise k and train a new network.
Similarly, if you switch functions (say f2 instead of f), then your ol network might also fail to do this.

Meaning, as the theorem says: Given f and given eps, there exists some k such that things check out.
But it's not the case that there's some one network which let you approximate ANY function to ANY precision.

----

Now let me cite the 3 mentions in your text verbatim

>The ability of a neural network to approximate any continuous function can be formally proven, and this is known as the universal approximation theorem.

>The width version of this theorem states that a network with one hidden layer containing a finite number of hidden units and an activation function can approximate any continuous function on a compact subset of Rn to arbitrary accuracy. This was proved by Cybenko (1989) for sigmoid activations and was later shown to be true for a larger class of nonlinear activation functions (Hornik, 1991).

>We argued in section 4.5.1 that if the layers of a deep network have enough hidden units, then the width version of the universal approximation theo- rem applies: the network can approximate any continuous function on a compact subset of RDi to arbitrary accuracy.

Now while the first 2 versions, with one eye closed, could maybe pass - the third version rather clearly claims there "the network" can approximate any function to any accuracy.
That's what I meant with you switched the quantifier around. The sentences don't really reflect the
"forall f, forall eps, there exists net, such that accurate"
It seems to say
"there exists net, such forall f, forall eps, accurate"
I think the fix isn't too hard, you just say something along the lines "the theorem is ... for any function and prec, some network exists"

-----

PS: There's another issue which might be misleading. Refering to the second quotation of mine, of your text.

In your text you introduce the logistic sigmoid function, and it makes it sound the late 80's paper concerned this 1/(1+exp(-x)) function. But from skimming the references and texts such as the PhD I cited, it seems already the 80's paper means, under "sigmoidal function" an extremely general class of continuous and nicely integrable functions. 
Here's e.g. the original text

<img width="653" alt="Bildschirmfoto 2023-05-31 um 22 27 20" src="https://github.com/udlbook/udlbook/assets/27020510/0ba21223-1c39-4f54-a7a5-604df76adfd9">

Hope that helps.

**Comment by Nikolaj-K** [comment]
Huh, scrolling down the article, it looks like when the target f is very nicely behaved (finite integral properties) and \sigma fulfills a similar condition, then the result was already known in the 30's

https://en.wikipedia.org/wiki/Wiener%27s_Tauberian_theorem

(bottom row in the pic references the Rudin textbook from the 70's, but Wikipedia cites Wiener for the related thing)

<img width="933" alt="Bildschirmfoto 2023-05-31 um 23 10 05" src="https://github.com/udlbook/udlbook/assets/27020510/a1d4c71d-96c2-42e5-88a6-14bbc5c79043">

**Comment by udlbook** [comment]
Thank you so much for going above and beyond to explain this to me.  I have tweaked the text in four places and I think it's more accurate now.

I really appreciate your help... and I learned something along the way.

**Comment by Nikolaj-K** [comment]
No problema, I learned something myself. If I find the time I might do a vid on it in the summer, I sometimes upload content [here](https://youtu.be/7jbZlurzpR4).
