### ISSUE TITLE
[Minor] Wrong Sub-Figure Referenced in Section 10.5.2 (Page 177) 

### ISSUE THREAD

**Issue by MasoudMo** [udlbook/udlbook#83]
In the second paragraph, figure 10.18b is referenced for the following sentence: "For each location, the output values also encode a fixed number of bounding boxes"

This does not seem to be correct as 10.18b is showing which class is chosen for each 7*7 grid and is not related to bounding boxes. I think changing the figure references to following could be more meaningful:

The output values encode which class is present at each of a 7×7 grid of locations (figure 10.18a-**b**). For each location, the output values also encode a fixed number of bounding boxes ~~(figure 10.18b)~~. Five parameters define each box: the x- and y-positions of the center, the height and width of the box, and the confidence of the prediction (figure 10.18c).

**Comment by udlbook** [comment]
Oohh.  Well spotted!  Thank you very much.  I've made the change you recommended and added your name to the acknowledgements.  Let me know if you find any more!
