### ISSUE TITLE
Thought on visualization colors

### ISSUE THREAD

**Issue by wwarriner** [udlbook/udlbook#84]
I am looking forward to this book, this has been a gap in my understanding of DL, as a research computing facilitator.

For plotting, you may enjoy this website with accessible, print-friendly, perceptually uniform, scientific color scales: 

Main site: https://www.fabiocrameri.ch/colourmaps/
Why-it-matters poster: https://s-ink.org/scientific-colour-map-poster

I also frequently use this Nature Methods short article for a small number of discrete colors. I think it is closely related to Cole Nussbaumer-Knaflic's color choices in Storytelling with Data.

https://www.nature.com/articles/nmeth.1618

If you have a source for the colors you have chosen, I would love to learn more about that!

**Comment by udlbook** [comment]
Thanks William,  

This is super useful.   I will take a close look.  I picked the colors somewhat randomly,  with the idea of defining a unique visual style for the book.  I somewhat regret that now as I don't think they are very good for colorblind people.
