### ISSUE TITLE
Ch 19: Bug in Fig. 19.8

### ISSUE THREAD

**Issue by sumit-research** [udlbook/udlbook#85]
<img width="201" alt="image" src="https://github.com/udlbook/udlbook/assets/35381448/ce80a49f-51cb-4e00-8d35-957969b5549c">

Here the action values for action a<sub>t</sub>=1 should be q[s<sub>t</sub> = 6, a<sub>t</sub>=1]. Likewise for a<sub>t</sub>=3. The corresponding equations seem to have been interchanged.

**Comment by udlbook** [comment]
Thanks, Sumit.  I fixed this and added your name to the acknowledgements at the start of the book.  Let me know if you find any more!
