### ISSUE TITLE
Problem 7.6 typo

### ISSUE THREAD

**Issue by victorsclui** [udlbook/udlbook#86]
In page 115 problem 7.6, rather than "∂zj/∂hi in its jth row and ith column", should it be "∂zj/∂hi in its ith row and jth column" instead? I think we are trying to look at the gradient matrix of vector function z, where ∂hi varies as we change row, and ∂zj varies as we change columns.

**Comment by udlbook** [comment]
Hi -  Thanks so much for the feedback and sorry about the long delay in replying.   I've rewritten the question and answer and I think this is fixed now.

Let me know if you find any more mistakes!  If you mail your full name to the address on the front of the manuscript, I will add you to the acknowledgements.
