### ISSUE TITLE
Zero Initialization

### ISSUE THREAD

**Issue by siavashk** [udlbook/udlbook#87]
I think Chapter 7 would benefit from an explanation of why zero initialization of neural networks is a bad idea. 
A natural place would be section 7.5.1, which would bump `Initialization for forward pass` to 7.5.2, the text would be something like this answer on [stats.stackexchange](https://stats.stackexchange.com/a/421687).

**Comment by udlbook** [comment]
Hi Siavash,

I think  this is really an extension of the discussion about He
initialization;  if the variance is too small (zero being the limit of
this), the gradients disappear.  I thought it was a good point though and I
added a problem about it.

Thanks so much for your help.  I added your name to the acknowledgements at
the start of the book.   Let me know if you have any more comments or find
any mistakes.

Simon
