### ISSUE TITLE
Clarification needed on how the convention works for dilations for convolutions in the book

### ISSUE THREAD

**Issue by trivikram-muralidharan** [udlbook/udlbook#89]
Hello,

First of all, thank you for writing this book on deep learning, I find it to be extremely useful and instructive.

I wanted to ask you about the default convention you have used for dilations in convolutional layers in the book - I believe that in the paper, the dilation values start from a default value of "1" (essentially, indicating "no dilation") and above. This is how dilations were introduced in the original paper as well - https://arxiv.org/pdf/1511.07122.pdf (search for the following text on page 2 of the paper - "The familiar discrete convolution ∗ is simply the 1-dilated convolution") 

I noticed that in several parts of the book (such as in Figure 10.3), including in some of the problems and exercises mentioned in the book (such as Problem 10.2), there are references to "0 dilation" - I think you meant "1-dilated convolution" in these locations.

I believe that the convention from the paper I mentioned is also followed in most library implementations of deep learning such as in pytorch (https://pytorch.org/docs/stable/generated/torch.nn.Conv1d.html) - notice that the default parameter for dilation for the convolution layer is 1 here.

Best Regards,
Trivikram Muralidharan

**Comment by udlbook** [comment]
Hey, apologies for not dealing with this more promptly.  I'm kind of overwhelmed, but I'll get to it!  

Your comments are definitely really appreciated.

**Comment by udlbook** [comment]
Hi Trivikram,  I finally had time to look into this, and you are completely correct.  Have fixed it now.  It will miss the first printing, but will be in the online version, and in future printed versions.  I've added your name to the acknowledgements at the start of the book.  Thanks so much for your help.
