### ISSUE TITLE
Some more minor issues

### ISSUE THREAD

**Issue by sfikas** [udlbook/udlbook#9]
Again on version 7-10-22-C5:

p.122: "ADAM" -> "Adam"
p.131:"Randomly which is inefficient": missing punctuation(??)
p.132: Missing reference to an Appendix
p.140: Missing reference to figure in figure 9.5 (probably to fig.8.1)
p.144: "this has smooths out the learned function"
p.145: "maximum-likelihoodcriterion"
p.146: Eq.9.11, change φ το φ' on the integral of the denominator?
p.154: "is not well understood although.." (missing a comma? unsure)

**Comment by sfikas** [comment]
"MNIST-1D" is used everywhere except Chapter 10 and the table of contents, where "MNIST1D" is used.
In pages 163 and 165 there are missing references to a figure, probably fig.8.1. 
In page 263 another reference to a figure is missing, "must be a contraction mapping (see figure ??)."

**Comment by udlbook** [comment]
Thanks so much.  You are of course technically right about the denominator of Bayes' rule (eq. 9.11) but I think the way that I have written it is the more common usage.  I think on balance changing the variable has to \phi' probably has just as much scope for confusion, so I left it.

The last missing reference is a forward reference to the normalizing flows chapter.  That's not public yet.  Hoping to get a few more chapters out in the next few weeks.   

Thank you again!
