### ISSUE TITLE
3_3_Shallow_Network_Regions.ipynb - number of parameters count

### ISSUE THREAD

**Issue by SergioGavichi** [udlbook/udlbook#94]
Hi,
The formula to count parameters has to be implemented as an exercise.
My formula does not match with the test you provide and I see you implement it further down to draw the nb of regions vs nb of parameters.
You use params[c_dim, c_hidden] =  D_i * D +1 + D +1, should it be   D_i * D + **D** + D +1 instead ? 
We have one Theta_x0 per hidden unit

Thanks

**Comment by udlbook** [comment]
Thanks so much for pointing this out.  I apologize.  Someone else has also spotted this out in the mean time and it should be fixed now already.  Actually, it's wrong in two places in that notebook.

Let me know if you find more.  Unfortunately, notebooks are not that well proofed.  Only so many hours in the day!
