### ISSUE TITLE
Latex embedding within jupyter notebooks doesn't consistently render in vscode

### ISSUE THREAD

**Issue by adamaviv** [udlbook/udlbook#98]
I know this is designed to be run in co-lab, but I think it would be great to also be able to do this locally on my own machine. I loaded the repo into vscode, and the latex embedding within vscode doesn't embed properly because vscode uses KaTex to render latex in markdown, but it seems that KaTex and MathJax (the default for Jupyter html output) have slightly different rules within markdown that cause some issues.

An example of this is in the first notebook [1_1_BackgroundMathematics.ipynb](https://github.com/udlbook/udlbook/blob/main/Notebooks/Chap01/1_1_BackgroundMathematics.ipynb) The first equation has the code:

```
\begin{equation}y=\beta+\omega x \end{equation} <br>
```

In vscode with KaTex this fails to render with the following errro

<img width="803" alt="image" src="https://github.com/udlbook/udlbook/assets/4605540/2747b4cf-f9ae-4f07-bd54-2bb232159003">

The error comes from the trailing `<br>`. Removing this you get the proper rendering. The same is true for the second equation in that block, the linear equation with two inputs.

Removing `<br>` helps a lot, but not universally. I'm also not sure why these are needed because markdown renderers atomically add breaks between distinct blocks. So they are redundant. 

However, there are other issues. Later in the same notebook, the following latex is included which is a parsing error

```
\begin{eqnarray}y_1 &=& \beta_1 + \omega_{11} x_1 + \omega_{12} x_2 + \omega_{13} x_3\\
y_2 &=& \beta_2 + \omega_{21} x_1 + \omega_{22} x_2 + \omega_{23} x_3.
\end{eqnarray}<br>
```

But removing the `<br>` doesn't solve this one as the issue is that `eqnarry` is not defined for KaTex (there's an open [ticket](https://github.com/KaTeX/KaTeX/issues/3643) for this), instead you are to use `align` like so to get the desired result (while removing `<br>`.

```
\begin{align}
y_1 &=& \beta_1 + \omega_{11} x_1 + \omega_{12} x_2 + \omega_{13} x_3\\
y_2 &=& \beta_2 + \omega_{21} x_1 + \omega_{22} x_2 + \omega_{23} x_3.
\end{align}
```

All to say, this is a systemic issue with the notebooks if one wants to run them in vscode, which I think many people might want to do. I can correct the first notebook and submit a pull request if it would be helpful for you to track the kinds of changes you need to make?

**Comment by adamaviv** [comment]
Sorry ... one more example with the latex issues is using `\mbox[exp]` which is also not supported by KaTEx, instead you could simply use `\exp` which is already defined and renders the same way.

**Comment by william-matz** [comment]
This script cleaned up 98% of the issues for me! Need to run it locally so I can work through the examples on a flight 😁 

```
import nbformat
import os
import re

def fix_latex_in_notebook(notebook_path):
    with open(notebook_path, 'r', encoding='utf-8') as file:
        nb = nbformat.read(file, as_version=4)

    for cell in nb.cells:
        if cell.cell_type == 'markdown':
            # Replace eqnarray with align
            cell.source = re.sub(r'\\begin\{eqnarray\*?\}', r'\\begin{align*}', cell.source)
            cell.source = re.sub(r'\\end\{eqnarray\*?\}', r'\\end{align*}', cell.source)
            
            # Remove <br> tags
            cell.source = re.sub(r'<br>', '', cell.source)
            
            # Enclose LaTeX blocks within $$...$$
            cell.source = re.sub(r'(\\begin\{align\}.*?\\end\{align\})', r'$$\1$$', cell.source, flags=re.DOTALL)
            
            # Replace \mbox with proper LaTeX commands
            cell.source = re.sub(r'\\mbox\{(.*?)\}', r'\1', cell.source)

    with open(notebook_path, 'w', encoding='utf-8') as file:
        nbformat.write(nb, file)

# Loop through all notebooks in a directory and its subdirectories
def process_all_notebooks(root_directory):
    for root, dirs, files in os.walk(root_directory):
        for file in files:
            if file.endswith('.ipynb'):
                try:
                    print('Processing', file)
                    notebook_path = os.path.join(root, file)
                    fix_latex_in_notebook(notebook_path)
                except:
                    print('Error processing', file)

process_all_notebooks('.')
```

**Comment by murphyk** [comment]
Thank you for this! It seems to help a lot. (I also wanted to work with the notebooks offline for a long flight :)

**Comment by udlbook** [comment]
Thanks so much for all of this help!  I'm completely slammed at the moment, and dropping many balls.  Two more weeks of teaching, but will get round to setting up VSCode and testing and updating all the notebooks in a few weeks.  In the meantime, hopefully, people can use this script as a workaround.

**Comment by udlbook** [comment]
Still completely underwater, but will get to this in the end.  It's going to be a big job to check that everything still works in both CoLab/Jupyter and locally (68 notebooks!), so this is going to have to be delayed for a little while.

Still grateful though and it's going to happen!

**Comment by udlbook** [comment]
Finally fixed this (manually)
